import * as fs from 'fs';
import * as path from 'path';
import { jsonSchemaToZod } from 'json-schema-to-zod';

async function syncContracts() {
  const schemaPath = path.join(process.cwd(), 'boomtick-pkg/cli/dev_tools/contract-schema.json');
  const outputPath = path.join(process.cwd(), 'boomtick-pkg/mcp/src/tools/contract.ts');

  if (!fs.existsSync(schemaPath)) {
    console.error(`Schema not found at ${schemaPath}`);
    process.exit(1);
  }

  const rawSchema = JSON.parse(fs.readFileSync(schemaPath, 'utf-8'));

  let tsContent = `// Automatically generated by sync-contracts.ts. Do not edit manually.\n`;
  tsContent += `import { z } from "zod";\n\n`;

  for (const [name, schema] of Object.entries(rawSchema)) {
    if (name.startsWith('_')) continue; // Skip metadata fields

    const zodCode = jsonSchemaToZod(schema as any, { name, module: 'esm' });

    // Use regex to capture the variable assignment part, allowing for multiline
    const match = zodCode.match(/export const \w+ = ([\s\S]*?);?\s*$/m);

    if (match) {
        let definition = match[1].trim();
        // Ensure it ends clean
        if (definition.endsWith(';')) definition = definition.slice(0, -1);

        tsContent += `export const ${name}Schema = ${definition}\n\n`;
        tsContent += `export type ${name} = z.infer<typeof ${name}Schema>;\n\n`;
    } else {
        console.warn(`Could not extract Zod definition for ${name}`);
    }
  }

  fs.writeFileSync(outputPath, tsContent);
  console.log(`Generated ${outputPath}`);
}

syncContracts().catch(err => {
  console.error(err);
  process.exit(1);
});
