import * as fs from 'fs';
import * as path from 'path';
import { jsonSchemaToZod } from 'json-schema-to-zod';

async function syncContracts() {
  const schemaPath = path.join(process.cwd(), 'boomtick-pkg/cli/dev_tools/cli-schema.json');
  const outputPath = path.join(process.cwd(), 'boomtick-pkg/mcp/src/tools/contract.ts');

  if (!fs.existsSync(schemaPath)) {
    console.error(`Schema not found at ${schemaPath}`);
    process.exit(1);
  }

  const rawSchema = JSON.parse(fs.readFileSync(schemaPath, 'utf-8'));
  const models = rawSchema.models || {};

  let tsContent = `// Automatically generated by sync-contracts.ts. Do not edit manually.\n`;
  tsContent += `import { z } from "zod";\n\n`;

  for (const [name, schema] of Object.entries(models)) {
    // Get the raw Zod expression without any variable assignment or imports
    const zodExpression = jsonSchemaToZod(schema as any, { module: 'none' });

    tsContent += `export const ${name}Schema = ${zodExpression};\n\n`;
    tsContent += `export type ${name} = z.infer<typeof ${name}Schema>;\n\n`;
  }

  fs.writeFileSync(outputPath, tsContent);
  console.log(`Generated ${outputPath}`);
}

syncContracts().catch(err => {
  console.error(err);
  process.exit(1);
});
