rules:
  - paths: '**/*.png'
    strategy: 'theirs'
  - paths: '**/*.jpg'
    strategy: 'theirs'
  - paths: '**/*.jpeg'
    strategy: 'theirs'
  - paths: '**/*.gif'
    strategy: 'theirs'
  - paths: '**/*.svg'
    strategy: 'theirs'
  - paths: '**/*.webp'
    strategy: 'theirs'
  - paths: 'pnpm-lock.yaml'
    strategy: 'theirs'
  - paths: '**/*'
    strategy: 'ours'
