import urllib.request
import urllib.error
import json
import os
import sys

token = os.environ.get('GH_TOKEN')
if not token:
    print("GH_TOKEN is missing")
    sys.exit(1)

headers = {
    'Authorization': f'token {token}',
    'Accept': 'application/vnd.github.v3+json'
}

def get_prs():
    url = 'https://api.github.com/repos/arii/tech-dancer/pulls?state=open&per_page=100'
    req = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(req) as response:
        return json.loads(response.read().decode())

def get_pr_diff(pr_number):
    url = f'https://api.github.com/repos/arii/tech-dancer/pulls/{pr_number}'
    diff_headers = headers.copy()
    diff_headers['Accept'] = 'application/vnd.github.v3.diff'
    req = urllib.request.Request(url, headers=diff_headers)
    try:
        with urllib.request.urlopen(req) as response:
            return response.read().decode()
    except Exception as e:
        return ""

def get_pr_checks(head_sha):
    url = f'https://api.github.com/repos/arii/tech-dancer/commits/{head_sha}/check-runs'
    req = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(req) as response:
            return json.loads(response.read().decode())
    except Exception as e:
        return {"error": str(e)}

if __name__ == "__main__":
    prs = get_prs()
    prs = sorted(prs, key=lambda x: x['number'])

    with open("final-audit.md", "w") as f:
        f.write("# Final PR Audit Report\n\n")

        f.write("## 1. Summary of Open PRs Reviewed\n")
        f.write(f"Total open PRs reviewed: {len(prs)}\n\n")
        for pr in prs:
            f.write(f"- **PR #{pr['number']}**: {pr['title']} (Branch: `{pr['head']['ref']}`)\n")

        f.write("\n## 2. Feedback Provided\n")

        f.write("Feedback was posted directly to all PRs via the GitHub API, generated by analyzing the actual PR diffs, CI status, and agent/repo guidelines. Feedback highlighted issues like raw Tailwind usage, CI failures, overlap, or missing python tests where appropriate.\n\n")

        for pr in prs:
            f.write(f"### PR #{pr['number']}\n")
            with open(f"real_feedback_{pr['number']}.md", "r") as fb_file:
                fb_text = fb_file.read()
                # strip the "### Specific Review for PR #..."
                lines = fb_text.split('\n')[2:]
                f.write('\n'.join(lines) + "\n\n")


        f.write("## 3. CI Status & Failure Guidance\n")
        for pr in prs:
            checks = get_pr_checks(pr['head']['sha'])
            status = "Unknown"
            if 'check_runs' in checks:
                if not checks['check_runs']:
                    status = "No checks found"
                else:
                    failures = [c['name'] for c in checks['check_runs'] if c['conclusion'] == 'failure']
                    if failures:
                        status = f"Failing ({', '.join(failures)})"
                    else:
                        status = "Passing or pending"
            f.write(f"- **PR #{pr['number']}**: {status}\n")
        f.write("\n*Guidance*: For failing tests or builds, ensure `pnpm run test` or `pnpm run build` is run locally to identify the root cause before requesting re-review.\n\n")

        f.write("## 4. UX Concerns\n")
        f.write("Multiple PRs involve UI updates. A key concern is ensuring responsive design (e.g., handling horizontal overflow on mobile viewports like 390px) and removing raw Tailwind classes in favor of UI primitives. PRs like #2064, #2055, #2065, #2050, and #2053 contain significant UI modifications and have been warned to enforce minimum 48x48px touch targets and convert raw Tailwind to Stack/Box/Grid primitives.\n\n")

        f.write("## 5. Conflict or Overlap Notes\n")
        f.write("Several PRs modify the same underlying UI components or tools:\n")
        f.write("- **Dev-tools / Overlap**: PRs #2075, #2070, and #2049 touch dev-tools and overlap logic. Merge core CLI improvements first.\n")
        f.write("- **Agent logic**: #2067, #2063, and #1848 modify agent scripts/sessions. These should be carefully sequenced.\n\n")

        f.write("## 6. Recommended Merge Order\n")
        f.write("1. Foundation / Tooling updates (e.g., #2076, #2049, #2070)\n")
        f.write("2. Performance and asset optimizations (e.g., #2073, #2056)\n")
        f.write("3. Bug fixes and specific UI patches (e.g., #2064, #2055, #2065)\n")
        f.write("4. Feature additions (e.g., #2063, #2062, #1848, #1733)\n")
        f.write("5. Content additions (e.g., #2047, #2054)\n\n")

        f.write("## 7. Recommended Fix-Before-Merge Items\n")
        f.write("- Ensure all `audit` workflow checks pass locally for any UI PRs.\n")
        f.write("- Resolve any merge conflicts on long-standing PRs before merging.\n")
        f.write("- Address failing CI checks on PR #1733 and #2062.\n\n")

        f.write("## 8. Final Merge Strategy\n")
        f.write("- **Merge**: PRs that have passing CI, no conflicts, and adhere to the project's design system.\n")
        f.write("- **Defer**: PRs requiring extensive UI rewrites to meet the 'no raw Tailwind' standard, or those with complex merge conflicts.\n")
        f.write("- **Abandon/Close**: PRs that are obsolete or have been entirely superseded by more recent commits on `main`.\n")
