import os
import re
import json
from typing import Dict, Any, List, Optional, Tuple
from dev_tools.utils import run_command, CLIError, get_any_count, get_bundle_size, walk_tsx, find_patterns_in_file, verify_pr_scope
from dev_tools.config import get_config

PROJECT_CONFIG = get_config()
SPEC_SECTIONS = PROJECT_CONFIG.spec_sections
AUDIT_CHECK_DIRS = PROJECT_CONFIG.audit_check_dirs

class AuditService:
    def __init__(self, orchestrator):
        self.orchestrator = orchestrator

    def get_audit_results(self, content: Optional[str] = None, targets: Optional[List[str]] = None) -> Dict[str, Any]:
        cmd = ["node", "scripts/detect-antipatterns.mjs", "--json"]
        if targets: cmd.extend(targets)
        elif content is not None: cmd.append("-")
        res = run_command(cmd, check=False, input_str=content)
        try: return json.loads(res.stdout)
        except json.JSONDecodeError: return {"violations": {}, "config": {}}

    def validate_issue(self, issue_number: Optional[int] = None, all_open: bool = False, post_comments: bool = False, dry_run: bool = True) -> Dict[str, Any]:
        from dev_tools.utils import get_github_client, get_repo_name
        repo = get_github_client().get_repo(get_repo_name())
        issues = list(repo.get_issues(state='open')) if all_open else [repo.get_issue(issue_number)] if issue_number else []
        if not issues: raise CLIError("Provide --issue-number or --all-open")
        results = []
        total_findings = 0
        audit_base = self.get_audit_results(content="")
        config = audit_base.get("config", {})
        for issue in issues:
            findings = []
            warnings = []
            body = issue.body or ''
            if not body.strip(): findings.append("Issue body is empty.")
            for i, block in enumerate(re.findall(r'```(?:tsx?|jsx?|html)?\n(.*?)```', body, re.DOTALL)):
                res = self.get_audit_results(content=block)
                for v in res.get("violations", {}).get("stdin", []):
                    findings.append(f"Code block {i+1}: {v['message']} (value: {v.get('value', 'N/A')})")
            for s in SPEC_SECTIONS:
                if not re.search(rf"^\s*(#+|\d+\.)\s*{re.escape(s)}\b", body, re.IGNORECASE | re.MULTILINE):
                    findings.append(f"Missing spec-driven sections: `{s}`")
            results.append({"number": issue.number, "title": issue.title, "findings": findings, "warnings": warnings})
            total_findings += len(findings)
            if post_comments and (findings or warnings) and not dry_run:
                issue.create_comment(f"## 🤖 Issue Quality Review\n\n### ❌ Violations\n" + "\n".join(f"- {f}" for f in findings) + f"\n\n---\n*Generated by `{PROJECT_CONFIG.cli_alias} validate-issue`*")
        return {"status": "success" if total_findings == 0 else "error", "issues": results, "total_findings": total_findings}

    def handle_audit_gate(self) -> Dict[str, Any]:
        current_count = int(run_command(["node", "scripts/detect-antipatterns.mjs", "--count-only"]) or 0)
        baseline_count = self.orchestrator.resolve_baseline(None, 'AUDIT_BASELINE', -1)
        if baseline_count == -1:
            baseline_count = 0
            base = PROJECT_CONFIG.base_branch
            base_files = run_command(["git", "ls-tree", "-r", base, "--name-only"]).splitlines()
            relevant = [mf for mf in base_files if (mf.endswith('.tsx') or mf.endswith('.ts')) and any(mf == d or mf.startswith(d + '/') for d in AUDIT_CHECK_DIRS)]
            for mf in relevant:
                res_show = run_command(["git", "show", f"{base}:{mf}"], check=False)
                if res_show.returncode == 0:
                    baseline_count += int(run_command(["node", "scripts/detect-antipatterns.mjs", "--count-only", "-"], input_str=res_show.stdout) or 0)
        return {"current": current_count, "baseline": baseline_count, "status": "success" if current_count <= baseline_count else "error"}
