#!/usr/bin/env python3
"""
issue_updater.py

Scans open issues and posts clarification comments when:
1. Instructions reference components/hooks that have been renamed or moved
2. Code snippets use patterns banned after the issue was created
3. The issue references a component path that no longer exists

Usage: python3 dev-tools/issue_updater.py --dry-run
       python3 dev-tools/issue_updater.py --execute
"""

import sys
import re
import argparse
from github_utils import get_github_token, get_repo_name
from github import Github

RENAMED_ASSETS = {
    'accent-brand': 'accent',
    'useSearch': 'useSearchParam',
    'useGlobalSearch': 'useGlobalSearch', # Example of keeping it same if no change but used for validation
}

DEPRECATED_PATHS = {
    'src/components/common/': 'src/components/ui/',
}

BANNED_PATTERNS = [
    (r'HashRouter', 'HashRouter is banned. Use createBrowserRouter (AGENTS.md §9)'),
    (r"import React from 'react'", 'Unnecessary React import — React 17+ (AGENTS.md §4)'),
]

def check_issue(issue, dry_run=True):
    body = issue.body or ''
    findings = []

    # 1. Check for renamed assets
    for old, new in RENAMED_ASSETS.items():
        if old in body:
            findings.append(f"References deprecated name `{old}`. Use `{new}` instead.")

    # 2. Check for deprecated paths
    for old, new in DEPRECATED_PATHS.items():
        if old in body:
            findings.append(f"References deprecated path `{old}`. New location: `{new}`")

    # 3. Check for banned patterns in snippets
    for pattern, message in BANNED_PATTERNS:
        if re.search(pattern, body):
            findings.append(f"Contains banned pattern: {message}")

    if findings:
        comment = "## 🤖 Automated Issue Update\n\n"
        comment += "The following instructions in this issue may be outdated based on recent repository changes:\n\n"
        for f in findings:
            comment += f"- {f}\n"
        comment += "\n---\n*Generated by `dev-tools/issue_updater.py`*"

        print(f"[{'DRY-RUN' if dry_run else 'EXECUTE'}] Found {len(findings)} issues in #{issue.number}")
        if not dry_run:
            issue.create_comment(comment)
            print(f"✅ Posted update comment to #{issue.number}")
        else:
            print(f"Preview of comment for #{issue.number}:\n{comment}\n")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--dry-run', action='store_true', default=True)
    parser.add_argument('--execute', action='store_false', dest='dry_run')
    args = parser.parse_args()

    token = get_github_token()
    repo_name = get_repo_name()
    g = Github(token)
    repo = g.get_repo(repo_name)

    print(f"🔍 Scanning open issues in {repo_name}...")
    for issue in repo.get_issues(state='open'):
        check_issue(issue, args.dry_run)

if __name__ == '__main__':
    main()
