[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "error_rag"
version = "0.1.0"
description = "Minimal RAG CLI Tool"
authors = [
    { name="Tech-Dancer Team" }
]
requires-python = ">=3.8"
dependencies = [
    "python-dotenv",
    "pydantic",
    "click"
]

[project.scripts]
error-rag = "error_rag:main"
