[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tdw_services"
version = "0.1.0"
description = "Tech-Dancer DevTools SDK"
authors = [
    { name="Tech-Dancer Team" }
]
requires-python = ">=3.8"
dependencies = [
    "requests>=2.0.0",
    "packaging>=21.3",
    "google-genai",
    "python-dotenv",
    "pydantic",
    "click",
    "PyGithub",
    "semgrep",
    "chromadb>=1.5.9",
    "sentence-transformers>=5.6.0"
]

[project.scripts]
td-cli = "tdw_services.cli:cli"

[tool.setuptools.packages.find]
where = ["."]
include = ["tdw_services*", "dev_tools_sdk*"]

[tool.setuptools.package-data]
"*" = ["project_config.json", "cli-schema.json"]
