"""
submit_pr_review_data.py

Parses a completed pr-review-NUMBER.md document and submits the review via gh_collab.py.

The document structure (generated by fetch_pr_review_data.py) provides all needed info:
  - PR number from the title line
  - Overall review body from the json block in "## 🚀 Submission Steps"
  - Inline comments from each "Proposed inline comment" json block

Usage:
    python3 dev-tools/submit_pr_review_data.py /tmp/pr-review-163.md
    python3 dev-tools/submit_pr_review_data.py /tmp/pr-review-163.md --dry-run
"""

import json
import re
import subprocess
import sys
import os


PLACEHOLDER_PATTERNS = [
    r"<FILL IN",
    r"Feedback here",
    r"<slop findings>",
    r"<per-file summary>",
    r"Approved | Approved with Minor Changes | Not Approved",
]


def is_placeholder(text: str) -> bool:
    return any(re.search(p, text) for p in PLACEHOLDER_PATTERNS)


def extract_pr_number(lines: list[str]) -> str:
    """Extract PR number from the title line: # PR Review: #163 — ..."""
    for line in lines[:5]:
        m = re.search(r"#PR Review.*?#(\d+)", line.replace(" ", ""))
        if not m:
            m = re.search(r"#\s*(\d+)", line)
        if m:
            return m.group(1)
    return None


def extract_json_blocks(text: str) -> list[dict]:
    """Extract all ```json ... ``` blocks from text and parse them."""
    blocks = []
    for m in re.finditer(r"```json\s*\n(.*?)```", text, re.DOTALL):
        raw = m.group(1).strip()
        try:
            blocks.append((json.loads(raw), m.start()))
        except json.JSONDecodeError:
            pass
    return blocks


def parse_review_doc(path: str) -> tuple[str, str, list[dict]]:
    """
    Returns (pr_number, overall_body, inline_comments).
    Raises ValueError with a descriptive message if the document is incomplete.
    """
    with open(path, "r") as f:
        text = f.read()
    lines = text.splitlines()

    # ── PR number ──────────────────────────────────────────────────────────────
    pr_number = extract_pr_number(lines)
    if not pr_number:
        raise ValueError("Could not find PR number in the document title line.")

    # ── Overall body from Submission Steps json block ─────────────────────────
    submission_section_match = re.search(r"## 🚀 Submission Steps(.*)", text, re.DOTALL)
    if not submission_section_match:
        raise ValueError("Document is missing the '## 🚀 Submission Steps' section.")

    submission_text = submission_section_match.group(1)
    submission_blocks = extract_json_blocks(submission_text)
    if not submission_blocks:
        raise ValueError("No JSON block found in the Submission Steps section.")

    overall_body = submission_blocks[0][0].get("body", "")
    if is_placeholder(overall_body):
        raise ValueError(
            "Overall review body still contains placeholder text. "
            "Fill in ANTI-AI-SLOP, FINDINGS, and FINAL RECOMMENDATION before submitting."
        )

    # ── Inline comments from Proposed inline comment blocks ───────────────────
    # Find each "Proposed inline comment" marker and grab the next json block after it
    comment_pattern = re.compile(r"\*\*Proposed inline comment\*\*.*?\n(```json\s*\n.*?```)", re.DOTALL)
    inline_comments = []
    skipped = []

    for m in comment_pattern.finditer(text):
        raw_block = m.group(1)
        json_match = re.search(r"```json\s*\n(.*?)```", raw_block, re.DOTALL)
        if not json_match:
            continue
        try:
            comment = json.loads(json_match.group(1).strip())
        except json.JSONDecodeError as e:
            print(f"  ⚠️  Skipping malformed JSON block: {e}")
            continue

        body = comment.get("body", "")
        line = comment.get("line", 1)
        path_str = comment.get("path", "")

        if is_placeholder(body):
            skipped.append(path_str)
            continue
        if line == 1:
            print(f"  ⚠️  Warning: `{path_str}` still has line=1 (default). Ensure this is intentional.")

        inline_comments.append({"path": path_str, "line": line, "body": body})

    if skipped:
        print(f"\n  ⚠️  {len(skipped)} file(s) skipped (unfilled placeholders):")
        for s in skipped:
            print(f"       - {s}")
        print()

    return pr_number, overall_body, inline_comments


def main():
    if len(sys.argv) < 2 or sys.argv[1] in ("-h", "--help"):
        print(__doc__)
        sys.exit(0)

    doc_path = sys.argv[1]
    dry_run = "--dry-run" in sys.argv

    if not os.path.exists(doc_path):
        print(f"Error: File not found: {doc_path}")
        sys.exit(1)

    print(f"📄 Parsing: {doc_path}")

    try:
        pr_number, overall_body, inline_comments = parse_review_doc(doc_path)
    except ValueError as e:
        print(f"\n❌ {e}")
        sys.exit(1)

    print(f"   PR #{pr_number} — {len(inline_comments)} inline comment(s) extracted")

    # ── Build and write payload ────────────────────────────────────────────────
    payload = {"body": overall_body, "comments": inline_comments}
    payload_path = "/tmp/review_payload.json"
    with open(payload_path, "w") as f:
        json.dump(payload, f, indent=2)
    print(f"✅ Payload written: {payload_path}")

    # ── Submit via gh_collab.py ────────────────────────────────────────────────
    script_dir = os.path.dirname(os.path.abspath(__file__))
    gh_collab = os.path.join(script_dir, "gh_collab.py")

    cmd = ["python3", gh_collab, "review", pr_number, "--file", payload_path]
    if dry_run:
        cmd.insert(2, "--dry-run")

    result = subprocess.run(cmd, cwd=os.path.dirname(script_dir))
    sys.exit(result.returncode)


if __name__ == "__main__":
    main()
