import React, { useState, useEffect, useRef, useMemo } from 'react';
import { Box, Stack, Text, Grid } from '@/layouts/Primitives';
import { AgentDecisionTrace, AuditSession, ThemeDressCode } from '../types';
import { FlightBufferTimeline } from './FlightBufferTimeline';
import { downloadIcsFile } from '../utils/icsDownloader';
import {
  Download,
  CheckCircle2,
  X,
  FileText,
  Clock,
  MapPin,
  Calendar,
  Sparkles,
  Shirt,
} from 'lucide-react';
import { Icon } from '@/components/ui/Icon';

export interface AgentMindTraceProps {
  trace?: Partial<AgentDecisionTrace>;
  visualScheduleMarkdown?: string;
  className?: string;
  activeEventName?: string;
  selectedDivision?: string;
  selectedRole?: string;
}

const DEFAULT_ICS = `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//WCS Navigator//Agent Mind Calendar//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:WCS Navigator Schedule
BEGIN:VEVENT
SUMMARY:Novice Jack & Jill Prelims
DTSTART:20261016T230000Z
DTEND:20261017T010000Z
LOCATION:Grand Ballroom A
DESCRIPTION:Matched Division: Novice. Staging buffer applied.
END:VEVENT
BEGIN:VEVENT
SUMMARY:WCS Foundations Technique Workshop
DTSTART:20261017T170000Z
DTEND:20261017T183000Z
LOCATION:Studio B
DESCRIPTION:Matched Track: All-Levels Workshop.
END:VEVENT
END:VCALENDAR`;

export const AgentMindTrace: React.FC<AgentMindTraceProps> = ({
  trace,
  visualScheduleMarkdown,
  className,
  activeEventName = 'South Bay Dance Fling 2026',
  selectedDivision = 'novice',
  selectedRole = 'lead',
}) => {
  const [showToast, setShowToast] = useState(false);
  const [toastMessage, setToastMessage] = useState({ title: '', message: '', file: '' });

  const toastTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  useEffect(() => {
    return () => {
      if (toastTimeoutRef.current) {
        clearTimeout(toastTimeoutRef.current);
      }
    };
  }, []);

  const showFeedbackToast = (title: string, message: string, file: string) => {
    setToastMessage({ title, message, file });
    setShowToast(true);
    if (toastTimeoutRef.current) {
      clearTimeout(toastTimeoutRef.current);
    }
    toastTimeoutRef.current = setTimeout(() => {
      setShowToast(false);
    }, 4500);
  };

  const handleDownloadCalendar = () => {
    const icsString = trace?.icsContent || DEFAULT_ICS;
    downloadIcsFile(icsString, `${activeEventName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-schedule.ics`);
    showFeedbackToast(
      'Calendar Downloaded (.ics)',
      'is ready to import into Apple Calendar, Google Calendar, or Outlook.',
      'wcs-schedule.ics'
    );
  };

  const handleDownloadVisualSchedule = () => {
    const content = visualScheduleMarkdown || `# Personalized Itinerary for ${activeEventName}\nGenerated by WCS Navigator.`;
    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', 'wcs-visual-schedule.md');
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    showFeedbackToast(
      'Mobile Schedule Downloaded (.md)',
      'is ready to view on your device.',
      'wcs-visual-schedule.md'
    );
  };

  // Matched sessions only (included for this dancer's plan)
  const matchedSessions = useMemo(() => {
    const raw = trace?.sessions || [];
    return raw.filter((s) => s.status === 'included');
  }, [trace?.sessions]);

  // Group sessions by day
  const sessionsByDay = useMemo(() => {
    const friday = matchedSessions.filter((s) => s.time.toLowerCase().includes('fri'));
    const saturday = matchedSessions.filter((s) => s.time.toLowerCase().includes('sat'));
    const sunday = matchedSessions.filter((s) => s.time.toLowerCase().includes('sun'));

    return { friday, saturday, sunday };
  }, [matchedSessions]);

  const themesByDay = useMemo(() => {
    const rawThemes = trace?.themeDressCodes || [];
    const friday = rawThemes.find((t) => t.day.toLowerCase().includes('fri'));
    const saturday = rawThemes.find((t) => t.day.toLowerCase().includes('sat'));
    const sunday = rawThemes.find((t) => t.day.toLowerCase().includes('sun'));

    return { friday, saturday, sunday };
  }, [trace?.themeDressCodes]);

  const renderSessionCard = (session: AuditSession) => {
    const isCompetition =
      session.title.toLowerCase().includes('prelim') ||
      session.title.toLowerCase().includes('strictly') ||
      session.title.toLowerCase().includes('competition') ||
      session.title.toLowerCase().includes('staging');

    return (
      <div
        key={session.id}
        className={`p-4 rounded-xl border transition-all flex flex-col justify-between ${
          isCompetition
            ? 'bg-amber-950/15 border-brand-amber/35 shadow-sm'
            : 'bg-slate-900/70 border-white/10 hover:border-brand-cyan/40'
        }`}
      >
        <Stack gap={2}>
          <h4 className="font-bold text-sm text-white leading-snug">
            {session.title}
          </h4>

          <div className="flex items-center gap-4 text-xs font-mono text-slate-400 pt-0.5">
            <div className="flex items-center gap-1.5">
              <Clock className="w-3.5 h-3.5 text-brand-cyan shrink-0" />
              <span>{session.time}</span>
            </div>
            <div className="flex items-center gap-1.5">
              <MapPin className="w-3.5 h-3.5 text-slate-400 shrink-0" />
              <span>{session.location}</span>
            </div>
          </div>
        </Stack>
      </div>
    );
  };

  const renderThemeCard = (theme?: ThemeDressCode) => {
    if (!theme) return null;

    return (
      <div className="p-3 rounded-xl bg-slate-900/60 border border-white/10 text-xs my-1 flex flex-wrap items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <Shirt className="w-3.5 h-3.5 text-slate-300 shrink-0" />
          <span className="font-bold text-xs text-white font-mono">
            {theme.day} Theme: {theme.themeTitle}
          </span>
          <span className="text-[10px] font-mono text-slate-400">
            ({theme.vibe})
          </span>
        </div>
        <div className="flex flex-wrap items-center gap-1.5">
          {theme.recommendedAttire.map((attire, i) => (
            <span
              key={i}
              className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-white/[0.04] border border-white/10 text-slate-300"
            >
              {attire}
            </span>
          ))}
        </div>
      </div>
    );
  };

  return (
    <Stack gap={6} className={className} width="full">
      {/* Toast Notification */}
      {showToast && (
        <Box
          role="status"
          aria-live="polite"
          padding={4}
          radius="xl"
          border
          shadow="2xl"
          className="fixed bottom-6 right-4 sm:right-6 md:right-8 z-50 max-w-sm w-full bg-slate-900/95 backdrop-blur-xl border-brand-cyan/40 motion-safe:transition-all"
        >
          <Box display="flex" align="start" justify="between" gap={3}>
            <Box display="flex" align="start" gap={3}>
              <Box padding={1.5} radius="full" className="bg-brand-cyan/20 text-brand-cyan shrink-0">
                <Icon icon={CheckCircle2} size="sm" color="accent" />
              </Box>
              <Stack gap={0.5}>
                <Text weight="font-bold" size="sm" color="main">
                  {toastMessage.title}
                </Text>
                <Text size="xs" color="dim" leading="relaxed">
                  <span className="text-white font-mono font-semibold">{toastMessage.file}</span> {toastMessage.message}
                </Text>
              </Stack>
            </Box>
            <button
              type="button"
              aria-label="Dismiss notification"
              onClick={() => setShowToast(false)}
              className="text-text-dim hover:text-white"
            >
              <Icon icon={X} size="xs" />
            </button>
          </Box>
        </Box>
      )}

      {/* Clean Context Header & Action Bar */}
      <Box
        padding={4}
        radius="xl"
        border
        className="bg-slate-900/80 border-line/70 backdrop-blur-md flex flex-wrap items-center justify-between gap-4"
      >
        <div className="flex items-center flex-wrap gap-2 text-xs font-mono">
          <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-brand-cyan/15 text-brand-cyan font-bold border border-brand-cyan/30">
            <Sparkles className="w-3.5 h-3.5" />
            <span>Profile: {selectedDivision.toUpperCase()} {selectedRole.toUpperCase()}</span>
          </span>
          <span className="text-text-dim">•</span>
          <span className="text-text-dim">✈️ Landing Target: <strong className="text-text-main">{trace?.bufferTimeline?.latestFlightArrivalDeadline || '2:15 PM Fri'}</strong></span>
          <span className="text-text-dim">•</span>
          <span className="text-text-dim">🌙 Late-Night: <strong className="text-text-main">Active</strong></span>
        </div>

        {/* Action Buttons: Primary (.ics) & Secondary (.md) */}
        <div className="flex items-center gap-3">
          <button
            type="button"
            onClick={handleDownloadCalendar}
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg bg-brand-cyan hover:bg-brand-cyan/90 text-black font-bold text-xs font-mono shadow-[0_0_20px_rgba(0,255,255,0.3)] hover:shadow-[0_0_25px_rgba(0,255,255,0.5)] transition-all cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Add to Calendar (.ics)</span>
          </button>
          <button
            type="button"
            onClick={handleDownloadVisualSchedule}
            className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg bg-slate-900 hover:bg-slate-800 border border-line/70 text-text-dim hover:text-white text-xs font-mono transition-colors cursor-pointer"
          >
            <FileText className="w-3.5 h-3.5" />
            <span>Markdown (.md)</span>
          </button>
        </div>
      </Box>

      {/* UNIFIED CHRONOLOGICAL DAY-BY-DAY FEED */}
      <Stack gap={6} width="full">
        {/* FRIDAY SECTION */}
        <Stack gap={4} width="full" className="rounded-xl bg-slate-900/30 border border-line/40 p-5">
          <div className="flex items-center justify-between pb-2 border-b border-line/30">
            <div className="flex items-center gap-2">
              <Calendar className="w-4 h-4 text-brand-cyan" />
              <h3 className="font-bold text-base text-text-main">
                Friday — Arrival, Warmup &amp; Prelims
              </h3>
            </div>
            <span className="text-xs font-mono text-text-dim">Day 1</span>
          </div>

          {/* Event-Based Local Transit & Logistics */}
          <FlightBufferTimeline activeEventName={activeEventName} />

          {/* Friday Sessions */}
          {sessionsByDay.friday.length > 0 && (
            <Grid cols={{ default: 1, md: 2 }} gap={3}>
              {sessionsByDay.friday.map(renderSessionCard)}
            </Grid>
          )}

          {/* Friday Night Theme */}
          {renderThemeCard(themesByDay.friday)}
        </Stack>

        {/* SATURDAY SECTION */}
        <Stack gap={4} width="full" className="rounded-xl bg-slate-900/30 border border-line/40 p-5">
          <div className="flex items-center justify-between pb-2 border-b border-line/30">
            <div className="flex items-center gap-2">
              <Calendar className="w-4 h-4 text-brand-cyan" />
              <h3 className="font-bold text-base text-text-main">
                Saturday — Daytime Workshops &amp; Champions Gala
              </h3>
            </div>
            <span className="text-xs font-mono text-text-dim">Day 2</span>
          </div>

          {/* Saturday Sessions */}
          {sessionsByDay.saturday.length > 0 && (
            <Grid cols={{ default: 1, md: 2 }} gap={3}>
              {sessionsByDay.saturday.map(renderSessionCard)}
            </Grid>
          )}

          {/* Saturday Evening Theme */}
          {renderThemeCard(themesByDay.saturday)}
        </Stack>

        {/* SUNDAY SECTION */}
        <Stack gap={4} width="full" className="rounded-xl bg-slate-900/30 border border-line/40 p-5">
          <div className="flex items-center justify-between pb-2 border-b border-line/30">
            <div className="flex items-center gap-2">
              <Calendar className="w-4 h-4 text-brand-cyan" />
              <h3 className="font-bold text-base text-text-main">
                Sunday — Intensive Masterclasses &amp; Survivor Social
              </h3>
            </div>
            <span className="text-xs font-mono text-text-dim">Day 3</span>
          </div>

          {/* Sunday Sessions */}
          {sessionsByDay.sunday.length > 0 && (
            <Grid cols={{ default: 1, md: 2 }} gap={3}>
              {sessionsByDay.sunday.map(renderSessionCard)}
            </Grid>
          )}

          {/* Sunday Night Theme */}
          {renderThemeCard(themesByDay.sunday)}
        </Stack>
      </Stack>
    </Stack>
  );
};

export default AgentMindTrace;

