// Automatically generated by sync-contracts.ts. Do not edit manually.
import { z } from "zod";

export const AIFileReviewSchema = z.object({ "file": z.string().describe("The path of the file being reviewed."), "issues": z.array(z.any()).describe("List of findings in this file.").optional(), "verdict": z.string().describe("The verdict for this file (ok, needs_changes, blocking).") });

export type AIFileReview = z.infer<typeof AIFileReviewSchema>;

export const AIFileReviewJsonSchema = {
  "$defs": {
    "AIReviewIssue": {
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Unique identifier for the finding.",
          "title": "Id"
        },
        "line": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Line number where the issue occurs.",
          "title": "Line"
        },
        "file": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "File path (if not already scoped by AIFileReview).",
          "title": "File"
        },
        "severity": {
          "description": "The severity level.",
          "enum": [
            "error",
            "warn",
            "info"
          ],
          "title": "Severity",
          "type": "string"
        },
        "issue": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Description of the issue (alternative to 'comment').",
          "title": "Issue"
        },
        "comment": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Description of the issue.",
          "title": "Comment"
        },
        "status": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": "open",
          "description": "Status of the finding.",
          "title": "Status"
        },
        "confidence": {
          "description": "Confidence level of the AI.",
          "enum": [
            "high",
            "medium",
            "low"
          ],
          "title": "Confidence",
          "type": "string"
        },
        "counterexample": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Example of how to fix or why it fails.",
          "title": "Counterexample"
        },
        "snippet": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "The exact code snippet from the diff.",
          "title": "Snippet"
        }
      },
      "required": [
        "severity",
        "confidence"
      ],
      "title": "AIReviewIssue",
      "type": "object"
    }
  },
  "properties": {
    "file": {
      "description": "The path of the file being reviewed.",
      "title": "File",
      "type": "string"
    },
    "issues": {
      "description": "List of findings in this file.",
      "items": {
        "$ref": "#/$defs/AIReviewIssue"
      },
      "title": "Issues",
      "type": "array"
    },
    "verdict": {
      "description": "The verdict for this file (ok, needs_changes, blocking).",
      "title": "Verdict",
      "type": "string"
    }
  },
  "required": [
    "file",
    "verdict"
  ],
  "title": "AIFileReview",
  "type": "object"
} as const;

export const AIFullReviewSchema = z.object({ "file_reviews": z.array(z.any()).describe("Per-file review results.").optional(), "reviewComment": z.string().describe("Overall summary comment for the PR."), "labels": z.array(z.string()).describe("Suggested labels for the PR.").optional(), "recommendation": z.string().describe("Final recommendation (Approved, Not Approved, etc).") });

export type AIFullReview = z.infer<typeof AIFullReviewSchema>;

export const AIFullReviewJsonSchema = {
  "$defs": {
    "AIFileReview": {
      "properties": {
        "file": {
          "description": "The path of the file being reviewed.",
          "title": "File",
          "type": "string"
        },
        "issues": {
          "description": "List of findings in this file.",
          "items": {
            "$ref": "#/$defs/AIReviewIssue"
          },
          "title": "Issues",
          "type": "array"
        },
        "verdict": {
          "description": "The verdict for this file (ok, needs_changes, blocking).",
          "title": "Verdict",
          "type": "string"
        }
      },
      "required": [
        "file",
        "verdict"
      ],
      "title": "AIFileReview",
      "type": "object"
    },
    "AIReviewIssue": {
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Unique identifier for the finding.",
          "title": "Id"
        },
        "line": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Line number where the issue occurs.",
          "title": "Line"
        },
        "file": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "File path (if not already scoped by AIFileReview).",
          "title": "File"
        },
        "severity": {
          "description": "The severity level.",
          "enum": [
            "error",
            "warn",
            "info"
          ],
          "title": "Severity",
          "type": "string"
        },
        "issue": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Description of the issue (alternative to 'comment').",
          "title": "Issue"
        },
        "comment": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Description of the issue.",
          "title": "Comment"
        },
        "status": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": "open",
          "description": "Status of the finding.",
          "title": "Status"
        },
        "confidence": {
          "description": "Confidence level of the AI.",
          "enum": [
            "high",
            "medium",
            "low"
          ],
          "title": "Confidence",
          "type": "string"
        },
        "counterexample": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Example of how to fix or why it fails.",
          "title": "Counterexample"
        },
        "snippet": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "The exact code snippet from the diff.",
          "title": "Snippet"
        }
      },
      "required": [
        "severity",
        "confidence"
      ],
      "title": "AIReviewIssue",
      "type": "object"
    }
  },
  "properties": {
    "file_reviews": {
      "description": "Per-file review results.",
      "items": {
        "$ref": "#/$defs/AIFileReview"
      },
      "title": "File Reviews",
      "type": "array"
    },
    "reviewComment": {
      "description": "Overall summary comment for the PR.",
      "title": "Reviewcomment",
      "type": "string"
    },
    "labels": {
      "description": "Suggested labels for the PR.",
      "items": {
        "type": "string"
      },
      "title": "Labels",
      "type": "array"
    },
    "recommendation": {
      "description": "Final recommendation (Approved, Not Approved, etc).",
      "title": "Recommendation",
      "type": "string"
    }
  },
  "required": [
    "reviewComment",
    "recommendation"
  ],
  "title": "AIFullReview",
  "type": "object"
} as const;

export const AIReviewIssueSchema = z.object({ "id": z.union([z.string(), z.null()]).describe("Unique identifier for the finding.").default(null), "line": z.union([z.number().int(), z.null()]).describe("Line number where the issue occurs.").default(null), "file": z.union([z.string(), z.null()]).describe("File path (if not already scoped by AIFileReview).").default(null), "severity": z.enum(["error","warn","info"]).describe("The severity level."), "issue": z.union([z.string(), z.null()]).describe("Description of the issue (alternative to 'comment').").default(null), "comment": z.union([z.string(), z.null()]).describe("Description of the issue.").default(null), "status": z.union([z.string(), z.null()]).describe("Status of the finding.").default("open"), "confidence": z.enum(["high","medium","low"]).describe("Confidence level of the AI."), "counterexample": z.union([z.string(), z.null()]).describe("Example of how to fix or why it fails.").default(null), "snippet": z.union([z.string(), z.null()]).describe("The exact code snippet from the diff.").default(null) });

export type AIReviewIssue = z.infer<typeof AIReviewIssueSchema>;

export const AIReviewIssueJsonSchema = {
  "properties": {
    "id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Unique identifier for the finding.",
      "title": "Id"
    },
    "line": {
      "anyOf": [
        {
          "type": "integer"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Line number where the issue occurs.",
      "title": "Line"
    },
    "file": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "File path (if not already scoped by AIFileReview).",
      "title": "File"
    },
    "severity": {
      "description": "The severity level.",
      "enum": [
        "error",
        "warn",
        "info"
      ],
      "title": "Severity",
      "type": "string"
    },
    "issue": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Description of the issue (alternative to 'comment').",
      "title": "Issue"
    },
    "comment": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Description of the issue.",
      "title": "Comment"
    },
    "status": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": "open",
      "description": "Status of the finding.",
      "title": "Status"
    },
    "confidence": {
      "description": "Confidence level of the AI.",
      "enum": [
        "high",
        "medium",
        "low"
      ],
      "title": "Confidence",
      "type": "string"
    },
    "counterexample": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Example of how to fix or why it fails.",
      "title": "Counterexample"
    },
    "snippet": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "The exact code snippet from the diff.",
      "title": "Snippet"
    }
  },
  "required": [
    "severity",
    "confidence"
  ],
  "title": "AIReviewIssue",
  "type": "object"
} as const;

export const AISynthesisReviewSchema = z.object({ "reviewComment": z.string().describe("Overall summary comment for the PR."), "labels": z.array(z.string()).describe("Suggested labels for the PR.").optional(), "recommendation": z.string().describe("Final recommendation.") });

export type AISynthesisReview = z.infer<typeof AISynthesisReviewSchema>;

export const AISynthesisReviewJsonSchema = {
  "properties": {
    "reviewComment": {
      "description": "Overall summary comment for the PR.",
      "title": "Reviewcomment",
      "type": "string"
    },
    "labels": {
      "description": "Suggested labels for the PR.",
      "items": {
        "type": "string"
      },
      "title": "Labels",
      "type": "array"
    },
    "recommendation": {
      "description": "Final recommendation.",
      "title": "Recommendation",
      "type": "string"
    }
  },
  "required": [
    "reviewComment",
    "recommendation"
  ],
  "title": "AISynthesisReview",
  "type": "object"
} as const;

export const CheckoutBranchInputSchema = z.object({ "branch": z.string().describe("The name of the branch to checkout."), "worktreePath": z.union([z.string(), z.null()]).describe("Optional path to the worktree to perform the checkout in.").default(null) });

export type CheckoutBranchInput = z.infer<typeof CheckoutBranchInputSchema>;

export const CheckoutBranchInputJsonSchema = {
  "properties": {
    "branch": {
      "description": "The name of the branch to checkout.",
      "title": "Branch",
      "type": "string"
    },
    "worktreePath": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Optional path to the worktree to perform the checkout in.",
      "title": "Worktreepath"
    }
  },
  "required": [
    "branch"
  ],
  "title": "CheckoutBranchInput",
  "type": "object"
} as const;

export const CommentTriageSummaryInputSchema = z.object({ "prNumber": z.number().int().describe("The number of the original PR to comment on."), "body": z.string().describe("The content of the comment.") });

export type CommentTriageSummaryInput = z.infer<typeof CommentTriageSummaryInputSchema>;

export const CommentTriageSummaryInputJsonSchema = {
  "properties": {
    "prNumber": {
      "description": "The number of the original PR to comment on.",
      "title": "Prnumber",
      "type": "integer"
    },
    "body": {
      "description": "The content of the comment.",
      "title": "Body",
      "type": "string"
    }
  },
  "required": [
    "prNumber",
    "body"
  ],
  "title": "CommentTriageSummaryInput",
  "type": "object"
} as const;

export const CommitPatchInputSchema = z.object({ "worktreePath": z.string().describe("Path to the worktree where changes are made."), "message": z.string().describe("Commit message."), "allowedFiles": z.array(z.string()).describe("List of files that are allowed to be committed."), "writeMode": z.boolean().describe("Safety gate: Must be true to perform the commit.") });

export type CommitPatchInput = z.infer<typeof CommitPatchInputSchema>;

export const CommitPatchInputJsonSchema = {
  "properties": {
    "worktreePath": {
      "description": "Path to the worktree where changes are made.",
      "title": "Worktreepath",
      "type": "string"
    },
    "message": {
      "description": "Commit message.",
      "title": "Message",
      "type": "string"
    },
    "allowedFiles": {
      "description": "List of files that are allowed to be committed.",
      "items": {
        "type": "string"
      },
      "title": "Allowedfiles",
      "type": "array"
    },
    "writeMode": {
      "description": "Safety gate: Must be true to perform the commit.",
      "title": "Writemode",
      "type": "boolean"
    }
  },
  "required": [
    "worktreePath",
    "message",
    "allowedFiles",
    "writeMode"
  ],
  "title": "CommitPatchInput",
  "type": "object"
} as const;

export const CreateBranchInputSchema = z.object({ "branchName": z.string().describe("The name of the new branch"), "baseBranch": z.string().describe("Branch to branch off from").default("main") });

export type CreateBranchInput = z.infer<typeof CreateBranchInputSchema>;

export const CreateBranchInputJsonSchema = {
  "properties": {
    "branchName": {
      "description": "The name of the new branch",
      "title": "Branchname",
      "type": "string"
    },
    "baseBranch": {
      "default": "main",
      "description": "Branch to branch off from",
      "title": "Basebranch",
      "type": "string"
    }
  },
  "required": [
    "branchName"
  ],
  "title": "CreateBranchInput",
  "type": "object"
} as const;

export const CreateIssueInputSchema = z.object({ "title": z.string().min(1), "body": z.union([z.string().min(1), z.null()]).default(null), "file": z.union([z.string().min(1), z.null()]).default(null) });

export type CreateIssueInput = z.infer<typeof CreateIssueInputSchema>;

export const CreateIssueInputJsonSchema = {
  "properties": {
    "title": {
      "minLength": 1,
      "title": "Title",
      "type": "string"
    },
    "body": {
      "anyOf": [
        {
          "minLength": 1,
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Body"
    },
    "file": {
      "anyOf": [
        {
          "minLength": 1,
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "File"
    }
  },
  "required": [
    "title"
  ],
  "title": "CreateIssueInput",
  "type": "object"
} as const;

export const CreateIssueResponseSchema = z.object({ "status": z.string().default("success"), "message": z.union([z.string(), z.null()]).default(null), "data": z.union([z.any(), z.null()]).default(null), "issue": z.union([z.any(), z.null()]).default(null) });

export type CreateIssueResponse = z.infer<typeof CreateIssueResponseSchema>;

export const CreateIssueResponseJsonSchema = {
  "$defs": {
    "IssueSummary": {
      "properties": {
        "number": {
          "title": "Number",
          "type": "integer"
        },
        "title": {
          "title": "Title",
          "type": "string"
        },
        "html_url": {
          "title": "Html Url",
          "type": "string"
        },
        "state": {
          "title": "State",
          "type": "string"
        }
      },
      "required": [
        "number",
        "title",
        "html_url",
        "state"
      ],
      "title": "IssueSummary",
      "type": "object"
    }
  },
  "properties": {
    "status": {
      "default": "success",
      "title": "Status",
      "type": "string"
    },
    "message": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Message"
    },
    "data": {
      "anyOf": [
        {},
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Data"
    },
    "issue": {
      "anyOf": [
        {
          "$ref": "#/$defs/IssueSummary"
        },
        {
          "type": "null"
        }
      ],
      "default": null
    }
  },
  "title": "CreateIssueResponse",
  "type": "object"
} as const;

export const CreateJulesSessionInputSchema = z.object({ "task": z.string().describe("The instructions for Jules."), "branch": z.union([z.string(), z.null()]).describe("The base branch to start from (e.g., 'main').").default(null), "pr": z.union([z.number().int(), z.null()]).describe("The PR number to use as the base branch context.").default(null) });

export type CreateJulesSessionInput = z.infer<typeof CreateJulesSessionInputSchema>;

export const CreateJulesSessionInputJsonSchema = {
  "properties": {
    "task": {
      "description": "The instructions for Jules.",
      "title": "Task",
      "type": "string"
    },
    "branch": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "The base branch to start from (e.g., 'main').",
      "title": "Branch"
    },
    "pr": {
      "anyOf": [
        {
          "type": "integer"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "The PR number to use as the base branch context.",
      "title": "Pr"
    }
  },
  "required": [
    "task"
  ],
  "title": "CreateJulesSessionInput",
  "type": "object"
} as const;

export const CreatePullRequestInputSchema = z.object({ "title": z.string().describe("PR Title."), "body": z.string().describe("Description of changes."), "head": z.string().describe("The branch containing changes to merge."), "base": z.string().describe("The target branch to merge into.").default("main"), "draft": z.boolean().describe("Whether to create the PR as a draft.").default(false) });

export type CreatePullRequestInput = z.infer<typeof CreatePullRequestInputSchema>;

export const CreatePullRequestInputJsonSchema = {
  "properties": {
    "title": {
      "description": "PR Title.",
      "title": "Title",
      "type": "string"
    },
    "body": {
      "description": "Description of changes.",
      "title": "Body",
      "type": "string"
    },
    "head": {
      "description": "The branch containing changes to merge.",
      "title": "Head",
      "type": "string"
    },
    "base": {
      "default": "main",
      "description": "The target branch to merge into.",
      "title": "Base",
      "type": "string"
    },
    "draft": {
      "default": false,
      "description": "Whether to create the PR as a draft.",
      "title": "Draft",
      "type": "boolean"
    }
  },
  "required": [
    "title",
    "body",
    "head"
  ],
  "title": "CreatePullRequestInput",
  "type": "object"
} as const;

export const CreateRepairBranchInputSchema = z.object({ "prNumber": z.number().int().describe("The original pull request number to repair."), "repairBranchName": z.union([z.string(), z.null()]).describe("Optional custom name for the new repair branch.").default(null), "writeMode": z.boolean().describe("Safety gate: Must be true to perform branch creation and worktree setup.") });

export type CreateRepairBranchInput = z.infer<typeof CreateRepairBranchInputSchema>;

export const CreateRepairBranchInputJsonSchema = {
  "properties": {
    "prNumber": {
      "description": "The original pull request number to repair.",
      "title": "Prnumber",
      "type": "integer"
    },
    "repairBranchName": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Optional custom name for the new repair branch.",
      "title": "Repairbranchname"
    },
    "writeMode": {
      "description": "Safety gate: Must be true to perform branch creation and worktree setup.",
      "title": "Writemode",
      "type": "boolean"
    }
  },
  "required": [
    "prNumber",
    "writeMode"
  ],
  "title": "CreateRepairBranchInput",
  "type": "object"
} as const;

export const GetChangedFilesInputSchema = z.object({ "base": z.string().describe("The base ref to compare from (default: 'main').").default("main"), "head": z.string().describe("The head ref to compare to (default: 'HEAD').").default("HEAD") });

export type GetChangedFilesInput = z.infer<typeof GetChangedFilesInputSchema>;

export const GetChangedFilesInputJsonSchema = {
  "properties": {
    "base": {
      "default": "main",
      "description": "The base ref to compare from (default: 'main').",
      "title": "Base",
      "type": "string"
    },
    "head": {
      "default": "HEAD",
      "description": "The head ref to compare to (default: 'HEAD').",
      "title": "Head",
      "type": "string"
    }
  },
  "title": "GetChangedFilesInput",
  "type": "object"
} as const;

export const GetMergeConflictFilesInputSchema = z.object({ "prNumber": z.number().int().describe("The number of the pull request to check for conflicts."), "baseBranch": z.string().describe("The base branch to check against (default: 'main').").default("main") });

export type GetMergeConflictFilesInput = z.infer<typeof GetMergeConflictFilesInputSchema>;

export const GetMergeConflictFilesInputJsonSchema = {
  "properties": {
    "prNumber": {
      "description": "The number of the pull request to check for conflicts.",
      "title": "Prnumber",
      "type": "integer"
    },
    "baseBranch": {
      "default": "main",
      "description": "The base branch to check against (default: 'main').",
      "title": "Basebranch",
      "type": "string"
    }
  },
  "required": [
    "prNumber"
  ],
  "title": "GetMergeConflictFilesInput",
  "type": "object"
} as const;

export const GetPackageScriptsInputSchema = z.object({ "filter": z.union([z.string(), z.null()]).describe("Optional glob pattern to filter script names.").default(null) });

export type GetPackageScriptsInput = z.infer<typeof GetPackageScriptsInputSchema>;

export const GetPackageScriptsInputJsonSchema = {
  "properties": {
    "filter": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Optional glob pattern to filter script names.",
      "title": "Filter"
    }
  },
  "title": "GetPackageScriptsInput",
  "type": "object"
} as const;

export const GetPrDiffInputSchema = z.object({ "prNumber": z.number().int().describe("The number of the pull request to get the diff for.") });

export type GetPrDiffInput = z.infer<typeof GetPrDiffInputSchema>;

export const GetPrDiffInputJsonSchema = {
  "properties": {
    "prNumber": {
      "description": "The number of the pull request to get the diff for.",
      "title": "Prnumber",
      "type": "integer"
    }
  },
  "required": [
    "prNumber"
  ],
  "title": "GetPrDiffInput",
  "type": "object"
} as const;

export const GetPrInputSchema = z.object({ "prNumber": z.number().int().describe("The number of the PR to view.") });

export type GetPrInput = z.infer<typeof GetPrInputSchema>;

export const GetPrInputJsonSchema = {
  "properties": {
    "prNumber": {
      "description": "The number of the PR to view.",
      "title": "Prnumber",
      "type": "integer"
    }
  },
  "required": [
    "prNumber"
  ],
  "title": "GetPrInput",
  "type": "object"
} as const;

export const GetRouteMapInputSchema = z.object({ "includeStatic": z.union([z.boolean(), z.null()]).describe("Whether to include static assets in the route map.").default(null) });

export type GetRouteMapInput = z.infer<typeof GetRouteMapInputSchema>;

export const GetRouteMapInputJsonSchema = {
  "properties": {
    "includeStatic": {
      "anyOf": [
        {
          "type": "boolean"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Whether to include static assets in the route map.",
      "title": "Includestatic"
    }
  },
  "title": "GetRouteMapInput",
  "type": "object"
} as const;

export const HealthCheckInputSchema = z.object({ "checkDeep": z.boolean().describe("Whether to perform a deep health check including external dependencies.").default(false) });

export type HealthCheckInput = z.infer<typeof HealthCheckInputSchema>;

export const HealthCheckInputJsonSchema = {
  "properties": {
    "checkDeep": {
      "default": false,
      "description": "Whether to perform a deep health check including external dependencies.",
      "title": "Checkdeep",
      "type": "boolean"
    }
  },
  "title": "HealthCheckInput",
  "type": "object"
} as const;

export const IssueCommentInputSchema = z.object({ "issueNumber": z.number().int().describe("The number of the issue to comment on."), "body": z.string().describe("The content of the comment.") });

export type IssueCommentInput = z.infer<typeof IssueCommentInputSchema>;

export const IssueCommentInputJsonSchema = {
  "properties": {
    "issueNumber": {
      "description": "The number of the issue to comment on.",
      "title": "Issuenumber",
      "type": "integer"
    },
    "body": {
      "description": "The content of the comment.",
      "title": "Body",
      "type": "string"
    }
  },
  "required": [
    "issueNumber",
    "body"
  ],
  "title": "IssueCommentInput",
  "type": "object"
} as const;

export const IssueSummarySchema = z.object({ "number": z.number().int(), "title": z.string(), "html_url": z.string(), "state": z.string() });

export type IssueSummary = z.infer<typeof IssueSummarySchema>;

export const IssueSummaryJsonSchema = {
  "properties": {
    "number": {
      "title": "Number",
      "type": "integer"
    },
    "title": {
      "title": "Title",
      "type": "string"
    },
    "html_url": {
      "title": "Html Url",
      "type": "string"
    },
    "state": {
      "title": "State",
      "type": "string"
    }
  },
  "required": [
    "number",
    "title",
    "html_url",
    "state"
  ],
  "title": "IssueSummary",
  "type": "object"
} as const;

export const IssueUpdateInputSchema = z.object({ "issueNumber": z.number().int().describe("The number of the issue to update."), "body": z.union([z.string(), z.null()]).describe("The new body content for the issue.").default(null), "file": z.union([z.string(), z.null()]).describe("Path to file containing new issue body.").default(null), "labels": z.union([z.array(z.string()), z.null()]).describe("Comma-separated list of labels to set.").default(null), "addLabels": z.union([z.array(z.string()), z.null()]).describe("Comma-separated list of labels to add.").default(null), "removeLabels": z.union([z.array(z.string()), z.null()]).describe("Comma-separated list of labels to remove.").default(null), "state": z.union([z.string(), z.null()]).describe("The state to set the issue to (open or closed).").default(null) });

export type IssueUpdateInput = z.infer<typeof IssueUpdateInputSchema>;

export const IssueUpdateInputJsonSchema = {
  "properties": {
    "issueNumber": {
      "description": "The number of the issue to update.",
      "title": "Issuenumber",
      "type": "integer"
    },
    "body": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "The new body content for the issue.",
      "title": "Body"
    },
    "file": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Path to file containing new issue body.",
      "title": "File"
    },
    "labels": {
      "anyOf": [
        {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Comma-separated list of labels to set.",
      "title": "Labels"
    },
    "addLabels": {
      "anyOf": [
        {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Comma-separated list of labels to add.",
      "title": "Addlabels"
    },
    "removeLabels": {
      "anyOf": [
        {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Comma-separated list of labels to remove.",
      "title": "Removelabels"
    },
    "state": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "The state to set the issue to (open or closed).",
      "title": "State"
    }
  },
  "required": [
    "issueNumber"
  ],
  "title": "IssueUpdateInput",
  "type": "object"
} as const;

export const IssueUpdateResponseSchema = z.object({ "status": z.string().default("success"), "message": z.union([z.string(), z.null()]).default(null), "data": z.union([z.any(), z.null()]).default(null), "issue": z.union([z.any(), z.null()]).default(null) });

export type IssueUpdateResponse = z.infer<typeof IssueUpdateResponseSchema>;

export const IssueUpdateResponseJsonSchema = {
  "$defs": {
    "IssueSummary": {
      "properties": {
        "number": {
          "title": "Number",
          "type": "integer"
        },
        "title": {
          "title": "Title",
          "type": "string"
        },
        "html_url": {
          "title": "Html Url",
          "type": "string"
        },
        "state": {
          "title": "State",
          "type": "string"
        }
      },
      "required": [
        "number",
        "title",
        "html_url",
        "state"
      ],
      "title": "IssueSummary",
      "type": "object"
    }
  },
  "properties": {
    "status": {
      "default": "success",
      "title": "Status",
      "type": "string"
    },
    "message": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Message"
    },
    "data": {
      "anyOf": [
        {},
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Data"
    },
    "issue": {
      "anyOf": [
        {
          "$ref": "#/$defs/IssueSummary"
        },
        {
          "type": "null"
        }
      ],
      "default": null
    }
  },
  "title": "IssueUpdateResponse",
  "type": "object"
} as const;

export const IssueViewInputSchema = z.object({ "issueNumber": z.number().int().describe("The number of the issue to view.") });

export type IssueViewInput = z.infer<typeof IssueViewInputSchema>;

export const IssueViewInputJsonSchema = {
  "properties": {
    "issueNumber": {
      "description": "The number of the issue to view.",
      "title": "Issuenumber",
      "type": "integer"
    }
  },
  "required": [
    "issueNumber"
  ],
  "title": "IssueViewInput",
  "type": "object"
} as const;

export const JulesListSessionsInputSchema = z.object({ "pageSize": z.union([z.number().int(), z.null()]).describe("Maximum number of sessions to return.").default(null), "pageToken": z.union([z.string(), z.null()]).describe("Token for pagination.").default(null) });

export type JulesListSessionsInput = z.infer<typeof JulesListSessionsInputSchema>;

export const JulesListSessionsInputJsonSchema = {
  "properties": {
    "pageSize": {
      "anyOf": [
        {
          "type": "integer"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Maximum number of sessions to return.",
      "title": "Pagesize"
    },
    "pageToken": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Token for pagination.",
      "title": "Pagetoken"
    }
  },
  "title": "JulesListSessionsInput",
  "type": "object"
} as const;

export const JulesSendMessageInputSchema = z.object({ "sessionId": z.union([z.string(), z.array(z.string())]).describe("The unique ID or IDs of the Jules session(s)."), "message": z.string().min(1).describe("The message content to send.") });

export type JulesSendMessageInput = z.infer<typeof JulesSendMessageInputSchema>;

export const JulesSendMessageInputJsonSchema = {
  "properties": {
    "sessionId": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      ],
      "description": "The unique ID or IDs of the Jules session(s).",
      "title": "Sessionid"
    },
    "message": {
      "description": "The message content to send.",
      "minLength": 1,
      "title": "Message",
      "type": "string"
    }
  },
  "required": [
    "sessionId",
    "message"
  ],
  "title": "JulesSendMessageInput",
  "type": "object"
} as const;

export const JulesSessionIdInputSchema = z.object({ "sessionId": z.string().describe("The unique ID of the Jules session.") });

export type JulesSessionIdInput = z.infer<typeof JulesSessionIdInputSchema>;

export const JulesSessionIdInputJsonSchema = {
  "properties": {
    "sessionId": {
      "description": "The unique ID of the Jules session.",
      "title": "Sessionid",
      "type": "string"
    }
  },
  "required": [
    "sessionId"
  ],
  "title": "JulesSessionIdInput",
  "type": "object"
} as const;

export const OpenReplacementPrInputSchema = z.object({ "originalPrNumber": z.number().int().describe("The number of the pull request being replaced."), "repairBranch": z.string().describe("The branch containing the fixes."), "baseBranch": z.string().describe("The branch to merge the fixes into."), "title": z.string().describe("The title of the new PR."), "body": z.string().describe("The body/description of the new PR."), "draft": z.boolean().describe("Whether to create the PR as a draft (default: true).").default(true), "worktreePath": z.union([z.string(), z.null()]).describe("Optional path to the worktree where the PR is created from.").default(null), "pushMode": z.boolean().describe("Safety gate: Must be true to push the branch and open the PR.") });

export type OpenReplacementPrInput = z.infer<typeof OpenReplacementPrInputSchema>;

export const OpenReplacementPrInputJsonSchema = {
  "properties": {
    "originalPrNumber": {
      "description": "The number of the pull request being replaced.",
      "title": "Originalprnumber",
      "type": "integer"
    },
    "repairBranch": {
      "description": "The branch containing the fixes.",
      "title": "Repairbranch",
      "type": "string"
    },
    "baseBranch": {
      "description": "The branch to merge the fixes into.",
      "title": "Basebranch",
      "type": "string"
    },
    "title": {
      "description": "The title of the new PR.",
      "title": "Title",
      "type": "string"
    },
    "body": {
      "description": "The body/description of the new PR.",
      "title": "Body",
      "type": "string"
    },
    "draft": {
      "default": true,
      "description": "Whether to create the PR as a draft (default: true).",
      "title": "Draft",
      "type": "boolean"
    },
    "worktreePath": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Optional path to the worktree where the PR is created from.",
      "title": "Worktreepath"
    },
    "pushMode": {
      "description": "Safety gate: Must be true to push the branch and open the PR.",
      "title": "Pushmode",
      "type": "boolean"
    }
  },
  "required": [
    "originalPrNumber",
    "repairBranch",
    "baseBranch",
    "title",
    "body",
    "pushMode"
  ],
  "title": "OpenReplacementPrInput",
  "type": "object"
} as const;

export const PRCommentSchema = z.object({ "user": z.string(), "body": z.string(), "created_at": z.string() });

export type PRComment = z.infer<typeof PRCommentSchema>;

export const PRCommentJsonSchema = {
  "properties": {
    "user": {
      "title": "User",
      "type": "string"
    },
    "body": {
      "title": "Body",
      "type": "string"
    },
    "created_at": {
      "title": "Created At",
      "type": "string"
    }
  },
  "required": [
    "user",
    "body",
    "created_at"
  ],
  "title": "PRComment",
  "type": "object"
} as const;

export const PRSummarySchema = z.object({ "number": z.number().int(), "title": z.string(), "author": z.record(z.string(), z.string()).optional(), "headRefName": z.union([z.string(), z.null()]).default(null), "baseRefName": z.union([z.string(), z.null()]).default(null), "isDraft": z.boolean().default(false), "mergeStateStatus": z.union([z.string(), z.null()]).default(null), "updatedAt": z.union([z.string(), z.null()]).default(null), "url": z.union([z.string(), z.null()]).default(null) });

export type PRSummary = z.infer<typeof PRSummarySchema>;

export const PRSummaryJsonSchema = {
  "properties": {
    "number": {
      "title": "Number",
      "type": "integer"
    },
    "title": {
      "title": "Title",
      "type": "string"
    },
    "author": {
      "additionalProperties": {
        "type": "string"
      },
      "title": "Author",
      "type": "object"
    },
    "headRefName": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Headrefname"
    },
    "baseRefName": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Baserefname"
    },
    "isDraft": {
      "default": false,
      "title": "Isdraft",
      "type": "boolean"
    },
    "mergeStateStatus": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Mergestatestatus"
    },
    "updatedAt": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Updatedat"
    },
    "url": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Url"
    }
  },
  "required": [
    "number",
    "title"
  ],
  "title": "PRSummary",
  "type": "object"
} as const;

export const ReadAgentContextInputSchema = z.object({});

export type ReadAgentContextInput = z.infer<typeof ReadAgentContextInputSchema>;

export const ReadAgentContextInputJsonSchema = {
  "properties": {},
  "title": "ReadAgentContextInput",
  "type": "object"
} as const;

export const ReadCiLogsInputSchema = z.object({ "prNumber": z.number().int().describe("The number of the pull request to read logs for."), "all": z.boolean().describe("Include logs for successful runs (default: false).").default(false) });

export type ReadCiLogsInput = z.infer<typeof ReadCiLogsInputSchema>;

export const ReadCiLogsInputJsonSchema = {
  "properties": {
    "prNumber": {
      "description": "The number of the pull request to read logs for.",
      "title": "Prnumber",
      "type": "integer"
    },
    "all": {
      "default": false,
      "description": "Include logs for successful runs (default: false).",
      "title": "All",
      "type": "boolean"
    }
  },
  "required": [
    "prNumber"
  ],
  "title": "ReadCiLogsInput",
  "type": "object"
} as const;

export const ReadPRCommentsInputSchema = z.object({ "prNumber": z.number().int().gt(0).describe("The PR number to fetch comments for.") });

export type ReadPRCommentsInput = z.infer<typeof ReadPRCommentsInputSchema>;

export const ReadPRCommentsInputJsonSchema = {
  "properties": {
    "prNumber": {
      "description": "The PR number to fetch comments for.",
      "exclusiveMinimum": 0,
      "title": "Prnumber",
      "type": "integer"
    }
  },
  "required": [
    "prNumber"
  ],
  "title": "ReadPRCommentsInput",
  "type": "object"
} as const;

export const ReadPRCommentsResponseSchema = z.object({ "status": z.string().default("success"), "message": z.union([z.string(), z.null()]).default(null), "data": z.union([z.any(), z.null()]).default(null), "pr": z.any(), "comments": z.array(z.any()).optional(), "review_comments": z.array(z.any()).optional() });

export type ReadPRCommentsResponse = z.infer<typeof ReadPRCommentsResponseSchema>;

export const ReadPRCommentsResponseJsonSchema = {
  "$defs": {
    "IssueSummary": {
      "properties": {
        "number": {
          "title": "Number",
          "type": "integer"
        },
        "title": {
          "title": "Title",
          "type": "string"
        },
        "html_url": {
          "title": "Html Url",
          "type": "string"
        },
        "state": {
          "title": "State",
          "type": "string"
        }
      },
      "required": [
        "number",
        "title",
        "html_url",
        "state"
      ],
      "title": "IssueSummary",
      "type": "object"
    },
    "PRComment": {
      "properties": {
        "user": {
          "title": "User",
          "type": "string"
        },
        "body": {
          "title": "Body",
          "type": "string"
        },
        "created_at": {
          "title": "Created At",
          "type": "string"
        }
      },
      "required": [
        "user",
        "body",
        "created_at"
      ],
      "title": "PRComment",
      "type": "object"
    },
    "ReviewComment": {
      "properties": {
        "user": {
          "title": "User",
          "type": "string"
        },
        "path": {
          "title": "Path",
          "type": "string"
        },
        "line": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Line"
        },
        "body": {
          "title": "Body",
          "type": "string"
        },
        "created_at": {
          "title": "Created At",
          "type": "string"
        }
      },
      "required": [
        "user",
        "path",
        "body",
        "created_at"
      ],
      "title": "ReviewComment",
      "type": "object"
    }
  },
  "properties": {
    "status": {
      "default": "success",
      "title": "Status",
      "type": "string"
    },
    "message": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Message"
    },
    "data": {
      "anyOf": [
        {},
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Data"
    },
    "pr": {
      "$ref": "#/$defs/IssueSummary"
    },
    "comments": {
      "items": {
        "$ref": "#/$defs/PRComment"
      },
      "title": "Comments",
      "type": "array"
    },
    "review_comments": {
      "items": {
        "$ref": "#/$defs/ReviewComment"
      },
      "title": "Review Comments",
      "type": "array"
    }
  },
  "required": [
    "pr"
  ],
  "title": "ReadPRCommentsResponse",
  "type": "object"
} as const;

export const RepoLogsInputSchema = z.object({ "prNumber": z.number().int().describe("The number of the pull request to stream logs for."), "grep": z.union([z.string(), z.null()]).describe("Optional pattern to filter log lines.").default(null) });

export type RepoLogsInput = z.infer<typeof RepoLogsInputSchema>;

export const RepoLogsInputJsonSchema = {
  "properties": {
    "prNumber": {
      "description": "The number of the pull request to stream logs for.",
      "title": "Prnumber",
      "type": "integer"
    },
    "grep": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Optional pattern to filter log lines.",
      "title": "Grep"
    }
  },
  "required": [
    "prNumber"
  ],
  "title": "RepoLogsInput",
  "type": "object"
} as const;

export const ReviewCommentSchema = z.object({ "user": z.string(), "path": z.string(), "line": z.union([z.number().int(), z.null()]).default(null), "body": z.string(), "created_at": z.string() });

export type ReviewComment = z.infer<typeof ReviewCommentSchema>;

export const ReviewCommentJsonSchema = {
  "properties": {
    "user": {
      "title": "User",
      "type": "string"
    },
    "path": {
      "title": "Path",
      "type": "string"
    },
    "line": {
      "anyOf": [
        {
          "type": "integer"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Line"
    },
    "body": {
      "title": "Body",
      "type": "string"
    },
    "created_at": {
      "title": "Created At",
      "type": "string"
    }
  },
  "required": [
    "user",
    "path",
    "body",
    "created_at"
  ],
  "title": "ReviewComment",
  "type": "object"
} as const;

export const RunLighthouseInputSchema = z.object({ "route": z.string().describe("The route to audit (default: '/').").default("/"), "worktreePath": z.union([z.string(), z.null()]).describe("Optional path to the worktree to run the audit in.").default(null) });

export type RunLighthouseInput = z.infer<typeof RunLighthouseInputSchema>;

export const RunLighthouseInputJsonSchema = {
  "properties": {
    "route": {
      "default": "/",
      "description": "The route to audit (default: '/').",
      "title": "Route",
      "type": "string"
    },
    "worktreePath": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Optional path to the worktree to run the audit in.",
      "title": "Worktreepath"
    }
  },
  "title": "RunLighthouseInput",
  "type": "object"
} as const;

export const RunPlaywrightInputSchema = z.object({ "grep": z.union([z.string(), z.null()]).describe("Optional pattern to filter tests by name.").default(null), "worktreePath": z.union([z.string(), z.null()]).describe("Optional path to the worktree to run tests in.").default(null) });

export type RunPlaywrightInput = z.infer<typeof RunPlaywrightInputSchema>;

export const RunPlaywrightInputJsonSchema = {
  "properties": {
    "grep": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Optional pattern to filter tests by name.",
      "title": "Grep"
    },
    "worktreePath": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Optional path to the worktree to run tests in.",
      "title": "Worktreepath"
    }
  },
  "title": "RunPlaywrightInput",
  "type": "object"
} as const;

export const RunTestsInputSchema = z.object({ "commands": z.union([z.array(z.string()), z.null()]).describe("Optional list of commands to run (default includes install, lint, test, build).").default(null), "timeoutSeconds": z.number().int().describe("Maximum time in seconds to wait for tests (default: 300).").default(300), "worktreePath": z.union([z.string(), z.null()]).describe("Optional path to the worktree to run tests in.").default(null) });

export type RunTestsInput = z.infer<typeof RunTestsInputSchema>;

export const RunTestsInputJsonSchema = {
  "properties": {
    "commands": {
      "anyOf": [
        {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Optional list of commands to run (default includes install, lint, test, build).",
      "title": "Commands"
    },
    "timeoutSeconds": {
      "default": 300,
      "description": "Maximum time in seconds to wait for tests (default: 300).",
      "title": "Timeoutseconds",
      "type": "integer"
    },
    "worktreePath": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Optional path to the worktree to run tests in.",
      "title": "Worktreepath"
    }
  },
  "title": "RunTestsInput",
  "type": "object"
} as const;

export const SearchDdgsInputSchema = z.object({ "query": z.string().describe("The search query."), "maxResults": z.union([z.number().int(), z.null()]).describe("Maximum number of results to return.").default(null) });

export type SearchDdgsInput = z.infer<typeof SearchDdgsInputSchema>;

export const SearchDdgsInputJsonSchema = {
  "properties": {
    "query": {
      "description": "The search query.",
      "title": "Query",
      "type": "string"
    },
    "maxResults": {
      "anyOf": [
        {
          "type": "integer"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Maximum number of results to return.",
      "title": "Maxresults"
    }
  },
  "required": [
    "query"
  ],
  "title": "SearchDdgsInput",
  "type": "object"
} as const;

export const SearchPRsInputSchema = z.object({ "state": z.string().describe("The state of the PRs to search for (open, closed, all).").default("open"), "limit": z.number().int().describe("The maximum number of PRs to return (default: 100, range: 1-100).").default(100), "includeDrafts": z.boolean().describe("Whether to include draft PRs in the results.").default(true), "labels": z.union([z.array(z.string()), z.null()]).describe("Filter PRs by labels.").default(null) });

export type SearchPRsInput = z.infer<typeof SearchPRsInputSchema>;

export const SearchPRsInputJsonSchema = {
  "properties": {
    "state": {
      "default": "open",
      "description": "The state of the PRs to search for (open, closed, all).",
      "title": "State",
      "type": "string"
    },
    "limit": {
      "default": 100,
      "description": "The maximum number of PRs to return (default: 100, range: 1-100).",
      "title": "Limit",
      "type": "integer"
    },
    "includeDrafts": {
      "default": true,
      "description": "Whether to include draft PRs in the results.",
      "title": "Includedrafts",
      "type": "boolean"
    },
    "labels": {
      "anyOf": [
        {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Filter PRs by labels.",
      "title": "Labels"
    }
  },
  "title": "SearchPRsInput",
  "type": "object"
} as const;

export const SearchPRsResponseSchema = z.object({ "status": z.string().default("success"), "message": z.union([z.string(), z.null()]).default(null), "data": z.union([z.any(), z.null()]).default(null), "prs": z.array(z.any()).optional() });

export type SearchPRsResponse = z.infer<typeof SearchPRsResponseSchema>;

export const SearchPRsResponseJsonSchema = {
  "$defs": {
    "PRSummary": {
      "properties": {
        "number": {
          "title": "Number",
          "type": "integer"
        },
        "title": {
          "title": "Title",
          "type": "string"
        },
        "author": {
          "additionalProperties": {
            "type": "string"
          },
          "title": "Author",
          "type": "object"
        },
        "headRefName": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Headrefname"
        },
        "baseRefName": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Baserefname"
        },
        "isDraft": {
          "default": false,
          "title": "Isdraft",
          "type": "boolean"
        },
        "mergeStateStatus": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Mergestatestatus"
        },
        "updatedAt": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Updatedat"
        },
        "url": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Url"
        }
      },
      "required": [
        "number",
        "title"
      ],
      "title": "PRSummary",
      "type": "object"
    }
  },
  "properties": {
    "status": {
      "default": "success",
      "title": "Status",
      "type": "string"
    },
    "message": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Message"
    },
    "data": {
      "anyOf": [
        {},
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Data"
    },
    "prs": {
      "items": {
        "$ref": "#/$defs/PRSummary"
      },
      "title": "Prs",
      "type": "array"
    }
  },
  "title": "SearchPRsResponse",
  "type": "object"
} as const;
