// Automatically generated by sync-contracts.ts. Do not edit manually.
import { z } from "zod";

export const CreateIssueInputSchema = z.object({ "title": z.string().min(1), "body": z.union([z.string().min(1), z.null()]).default(null), "file": z.union([z.string().min(1), z.null()]).default(null) });

export type CreateIssueInput = z.infer<typeof CreateIssueInputSchema>;

export const SearchPRsInputSchema = z.object({ "state": z.string().default("open"), "limit": z.number().int().default(100), "include_drafts": z.boolean().default(true), "labels": z.union([z.array(z.string()), z.null()]).default(null) });

export type SearchPRsInput = z.infer<typeof SearchPRsInputSchema>;

export const IssueUpdateInputSchema = z.object({ "issue_number": z.number().int(), "body": z.union([z.string(), z.null()]).default(null), "file": z.union([z.string(), z.null()]).default(null), "labels": z.union([z.array(z.string()), z.null()]).default(null), "add_labels": z.union([z.array(z.string()), z.null()]).default(null), "remove_labels": z.union([z.array(z.string()), z.null()]).default(null) });

export type IssueUpdateInput = z.infer<typeof IssueUpdateInputSchema>;

export const CreateIssueResponseSchema = z.object({ "status": z.string().default("success"), "message": z.union([z.string(), z.null()]).default(null), "data": z.union([z.any(), z.null()]).default(null), "issue": z.union([z.any(), z.null()]).default(null) });

export type CreateIssueResponse = z.infer<typeof CreateIssueResponseSchema>;

export const SearchPRsResponseSchema = z.object({ "status": z.string().default("success"), "message": z.union([z.string(), z.null()]).default(null), "data": z.union([z.any(), z.null()]).default(null), "prs": z.array(z.any()).optional() });

export type SearchPRsResponse = z.infer<typeof SearchPRsResponseSchema>;

export const IssueUpdateResponseSchema = z.object({ "status": z.string().default("success"), "message": z.union([z.string(), z.null()]).default(null), "data": z.union([z.any(), z.null()]).default(null), "issue": z.union([z.any(), z.null()]).default(null) });

export type IssueUpdateResponse = z.infer<typeof IssueUpdateResponseSchema>;
