import { useState } from 'react';
import { Box, Stack, Text } from '@/layouts/Primitives';
import { PageHeader } from '@/components/ui/PageHeader';
import { SEO } from '@/components/SEO';
import { Icon } from '@/components/ui/Icon';
import { HelpCircle, ArrowLeft, Layers } from 'lucide-react';
import { CALIFORNIA_2026_EVENTS } from './data/californiaEvents';
import { MOCK_EVENT_RESULTS, createGenericMockResult, EventMockData } from './data/mockResults';
import { EventSearchHero } from './components/EventSearchHero';
import { AgentDiscoveryTransition } from './components/AgentDiscoveryTransition';
import { DynamicQuestionnaire } from './components/DynamicQuestionnaire';
import { AgentMindTrace } from './components/AgentMindTrace';
import { WorkflowExplainer } from './components/WorkflowExplainer';
import { DiscoveryResponse, QuestionAnswerValue } from './types/navigator';
import { AgentDecisionTrace } from './types';

type WizardStep = 'search' | 'discovering' | 'questionnaire' | 'results';

export const WCSNavigatorPage: React.FC = () => {
  const [step, setStep] = useState<WizardStep>('search');
  const [isMockMode, setIsMockMode] = useState<boolean>(true);
  const [isGuideOpen, setIsGuideOpen] = useState<boolean>(false);

  // Selected State
  const [activeEventName, setActiveEventName] = useState<string>(CALIFORNIA_2026_EVENTS[0].name);
  const [activeEventId, setActiveEventId] = useState<string>(CALIFORNIA_2026_EVENTS[0].id);

  // Data State
  const [discoveryData, setDiscoveryData] = useState<DiscoveryResponse>(
    MOCK_EVENT_RESULTS['south-bay-dance-fling-2026'].discovery
  );
  const [decisionTrace, setDecisionTrace] = useState<AgentDecisionTrace>(
    MOCK_EVENT_RESULTS['south-bay-dance-fling-2026'].decisionTrace
  );

  // Discovery handlers
  const handleStartDiscovery = (eventName: string, eventId?: string) => {
    setActiveEventName(eventName);
    setActiveEventId(eventId || '');
    setStep('discovering');
  };

  const handleDiscoveryComplete = () => {
    const mockData: EventMockData =
      MOCK_EVENT_RESULTS[activeEventId] || createGenericMockResult(activeEventName);

    setDiscoveryData(mockData.discovery);
    setDecisionTrace(mockData.decisionTrace);
    setStep('questionnaire');
  };

  // Questionnaire submission handler
  const handleGenerateItinerary = (_answers: Record<string, QuestionAnswerValue>) => {
    const mockData = MOCK_EVENT_RESULTS[activeEventId] || createGenericMockResult(activeEventName);
    setDecisionTrace(mockData.decisionTrace);

    const eventTitle = discoveryData?.preset_name || activeEventName;
    const buffer = mockData.decisionTrace.bufferTimeline;
    const sessions = mockData.decisionTrace.sessions || [];
    const themes = mockData.decisionTrace.themeDressCodes || [];

    const markdownDoc = [
      `# 🕺 ${eventTitle} — Personalized Weekend Itinerary`,
      `*Generated by WCS Navigator on ${new Date().toLocaleDateString()}*`,
      '',
      '## ✈️ Travel & Arrival Buffer Target',
      `- **Earliest Event Staging Call:** ${buffer?.earliestStagingTime || '5:15 PM Friday'}`,
      `- **Recommended Flight Touchdown:** ${buffer?.latestFlightArrivalDeadline || '2:15 PM Friday'}`,
      `- **Buffer Breakdown:** ${buffer?.transitMinutes || 30}m Transit + ${buffer?.hotelSettleMinutes || 90}m Hotel Settle + ${buffer?.warmupMinutes || 60}m Warmup`,
      '',
      '## 📅 Matched Workshops & Competition Schedule',
      ...sessions.filter(s => s.status === 'included').map(s => `### ✅ ${s.title}\n- **Time:** ${s.time}\n- **Location:** ${s.location}\n- **Profile Match:** ${s.justification}\n`),
      '',
      '## 🎭 Party Themes & Dress Codes',
      ...themes.map(t => `### 🌟 ${t.day}: ${t.themeTitle}\n- **Atmosphere:** ${t.vibe}\n- **Outfits:** ${t.recommendedAttire.join(', ')}\n`)
    ].join('\n');

    setDiscoveryData(prev => ({ ...prev, visualScheduleMarkdown: markdownDoc }));
    setStep('results');
  };

  return (
    <Box as="section" maxWidth="7xl" marginX="auto" width="full" paddingX={{ base: 4, sm: 6 }}>
      <SEO
        title="WCS Navigator — AI Dance Convention Itinerary & Calendar Optimizer"
        description="Google Search-style AI agent for West Coast Swing conventions. Pre-scans multi-room schedules, computes backward flight buffer math, and streams calendar files."
        keywords="West Coast Swing, WCS Navigator, AI dance optimizer, California 2026 WCS events, flight buffer engine, schedule parser"
      />

      <Stack gap={8} width="full">
        {/* Top Header & Minimal Mode Switcher */}
        <Box display="flex" justify="between" align="start" wrap="wrap" gap={4} className="pb-2 border-b border-line/40">
          <Stack gap={1}>
            <Box display="flex" align="center" gap={3}>
              <PageHeader
                title="WCS Navigator"
                as="h1"
                paddingBottom={0}
                border="none"
              />
              <Box
                as="button"
                type="button"
                aria-label="How WCS Navigator Works guide"
                onClick={() => setIsGuideOpen(!isGuideOpen)}
                className="text-xs font-mono text-text-dim hover:text-text-main flex items-center gap-1 cursor-pointer transition-colors"
              >
                <Icon icon={HelpCircle} size="xs" />
                <span className="underline underline-offset-2">How It Works</span>
              </Box>
            </Box>
            <Text size="xs" color="dim">
              Personalized weekend schedule and travel planner for California 2026 West Coast Swing conventions.
            </Text>
          </Stack>

          {/* Mode Switch: Text-only utility link */}
          <Box
            as="button"
            type="button"
            onClick={() => setIsMockMode(!isMockMode)}
            className="text-xs font-mono text-text-dim hover:text-text-main flex items-center gap-2 transition-colors cursor-pointer py-1"
          >
            <span className={`w-2 h-2 rounded-full ${isMockMode ? 'bg-slate-400' : 'bg-brand-emerald'}`} />
            <span>{isMockMode ? 'Demo Data' : 'Live Data'}</span>
          </Box>
        </Box>

        {/* Collapsible Inline Guide (Single Consolidated Container) */}
        {isGuideOpen && (
          <WorkflowExplainer onClose={() => setIsGuideOpen(false)} />
        )}

        {/* Step Progression Breadcrumb (Clean Text Flow) */}
        {step !== 'search' && (
          <Box
            display="flex"
            align="center"
            justify="between"
            wrap="wrap"
            gap={3}
            className="text-xs font-mono text-text-dim py-1"
          >
            <Box display="flex" align="center" gap={2}>
              <Box
                as="button"
                type="button"
                onClick={() => setStep('search')}
                className="text-text-dim hover:text-text-main transition-colors cursor-pointer"
              >
                ← Change
              </Box>
              <span className="text-line">/</span>
              <span className="text-text-main font-semibold">{activeEventName}</span>
            </Box>

            <Box
              as="button"
              type="button"
              onClick={() => setStep('search')}
              className="text-text-dim hover:text-text-main transition-colors cursor-pointer"
            >
              Start Over
            </Box>
          </Box>
        )}

        {/* STEP 1: Search & Ingestion Hero */}
        {step === 'search' && (
          <EventSearchHero
            onDiscoverPreset={(event) => handleStartDiscovery(event.name, event.id)}
            onDiscoverPdf={(file) => handleStartDiscovery(file.name.replace(/\.pdf$/i, ''))}
            onDiscoverUrl={(url) => handleStartDiscovery(url)}
          />
        )}

        {/* STEP 1.5: Animated Agent Discovery Scanning Transition */}
        {step === 'discovering' && (
          <AgentDiscoveryTransition
            eventName={activeEventName}
            onComplete={handleDiscoveryComplete}
          />
        )}

        {/* STEP 2: Discovered Dynamic Questionnaire & Persona Pre-Fill (Borderless clean layout) */}
        {step === 'questionnaire' && (
          <Stack gap={6} width="full" maxWidth="3xl" marginX="auto">
            <DynamicQuestionnaire
              discoveryResponse={discoveryData}
              onSubmit={handleGenerateItinerary}
            />
          </Stack>
        )}

        {/* STEP 3: Agent Mind Decision Explainer & Calendar Export */}
        {step === 'results' && (
          <Stack gap={6} width="full">
            <Box display="flex" justify="between" align="center" wrap="wrap" gap={3}>
              <Box
                as="button"
                type="button"
                onClick={() => setStep('questionnaire')}
                display="flex"
                align="center"
                gap={2}
                paddingX={4}
                paddingY={2.5}
                radius="lg"
                surface="surface"
                border
                minHeight="11"
                cursor="pointer"
                className="border-line text-xs font-bold text-dim hover:text-white hover:border-accent transition-all"
              >
                <Icon icon={ArrowLeft} size="xs" />
                <span>Adjust Preferences &amp; Re-generate</span>
              </Box>
            </Box>

            <AgentMindTrace
              trace={decisionTrace}
              visualScheduleMarkdown={(discoveryData?.visualScheduleMarkdown) || (discoveryData?.preset_name ? `# Your WCS Visual Schedule for ${discoveryData.preset_name}\n\nGenerated by WCS Navigator.` : undefined)}
            />
          </Stack>
        )}

        {/* Clean Footer Tag */}
        <Box display="flex" align="center" justify="center" gap={2} paddingY={4} color="dim">
          <Icon icon={Layers} size="xs" />
          <Text size="micro" variant="mono" color="dim">
            WCS Navigator • Personalized Itinerary &amp; Travel Planner
          </Text>
        </Box>
      </Stack>
    </Box>
  );
};
