export const HERO_CONFIG = {
  PARTICLE_COUNT: 30,
  PARTICLE_RADIUS_MIN: 0.4,
  PARTICLE_RADIUS_MAX: 1.8,
  PARTICLE_VELOCITY_FACTOR: 0.15,
  PARTICLE_ALPHA_MIN: 0.05,
  PARTICLE_ALPHA_MAX: 0.2,
  PARTICLE_HUES: [190, 270],
  // Performance tuning
  TARGET_FPS: 60,
  FRAME_JITTER: 0.1,
  RESIZE_DEBOUNCE_MS: 200,
  // Deterministic seeds for stable animations
  SEEDS: {
    PARTICLE_X: 777.7,
    PARTICLE_Y: 333.3,
    PARTICLE_R: 123.4,
    PARTICLE_VX: 555.5,
    PARTICLE_VY: 999.9,
    PARTICLE_ALPHA: 444.4,
  }
};
