export const HERO_CONFIG = {
  PARTICLE_COUNT: 60,
  PARTICLE_RADIUS_MIN: 0.4,
  PARTICLE_RADIUS_MAX: 1.8,
  PARTICLE_VELOCITY_FACTOR: 0.3,
  PARTICLE_ALPHA_MIN: 0.1,
  PARTICLE_ALPHA_MAX: 0.4,
  PARTICLE_HUES: [190, 270],
  BAR_COUNT: 48,
  MOBILE_PY: 6,
  DESKTOP_PY: 12,
};
