import * as fs from 'fs';
import * as path from 'path';
import { ARTIFACTS_DIR } from './visualReviewConstants';
import { postPRComment, countExistingReviews } from './visualReviewUtils';
import type { CodeReviewSummary, CodeReviewResult } from './codeReviewTypes';
import { execSync } from 'child_process';

export interface CodeReviewClientStrategy {
  botName: string;
  reportTitle: string;
  botTagline: string;
  reportFileName: string;
  invokeReview: (summary: CodeReviewSummary) => Promise<CodeReviewResult>;
}

const MAX_REVIEWS_PER_PR = parseInt(process.env.MAX_AI_REVIEWS ?? '2', 10);

export function getCodeDiffSummary(): CodeReviewSummary {
  try {
    const diffCommand = 'git diff origin/main...HEAD';
    const rawDiff = execSync(diffCommand, { encoding: 'utf-8', maxBuffer: 1024 * 1024 * 10 });

    // basic sanity check - just take the first N chars if it's absurdly large to avoid blowing up context
    const maxChars = 20000;
    const diffContext = rawDiff.length > maxChars
      ? rawDiff.slice(0, maxChars) + '\n\n...[TRUNCATED FOR LLM]'
      : rawDiff;

    const files = execSync('git diff --name-only origin/main...HEAD', { encoding: 'utf-8' })
      .split('\n')
      .filter(Boolean);

    return {
      files,
      diffContext
    };
  } catch (error) {
    console.warn('Could not generate code diff using origin/main...HEAD, falling back to cached/unstaged:', error);
    try {
        const staged = execSync('git diff --cached', { encoding: 'utf-8' });
        const unstaged = execSync('git diff', { encoding: 'utf-8' });
        const rawDiff = staged + '\n' + unstaged;

        const filesStaged = execSync('git diff --name-only --cached', { encoding: 'utf-8' }).split('\n').filter(Boolean);
        const filesUnstaged = execSync('git diff --name-only', { encoding: 'utf-8' }).split('\n').filter(Boolean);
        const files = Array.from(new Set([...filesStaged, ...filesUnstaged]));

        const diffContext = rawDiff.length > 20000
          ? rawDiff.slice(0, 20000) + '\n\n...[TRUNCATED FOR LLM]'
          : rawDiff;

        return { files, diffContext };
    } catch(fallbackError) {
        console.warn('Fallback failed:', fallbackError);
        return { files: [], diffContext: '' };
    }
  }
}

export function generateCodeReviewMarkdown(
  result: CodeReviewResult,
  client: CodeReviewClientStrategy
): string {
  const prNumber = process.env.PR_NUMBER;
  const prLink = prNumber ? `[PR #${prNumber}](https://github.com/${process.env.GITHUB_REPOSITORY}/pull/${prNumber})` : 'this PR';

  let costLine = '';
  if (result.cost > 0) {
    costLine = `**Cost:** ~$${result.cost.toFixed(5)} (${result.tokens} tokens)\n`;
  }

  return `## ${client.reportTitle}

> ${client.botTagline}

**Reviewing:** ${prLink}
${costLine}

### Code Review Feedback
${result.feedback}

---
*Generated by ${client.botName}*
`;
}

export async function orchestrateCodeReview(
  client: CodeReviewClientStrategy,
  allReportTitles: string[] = []
): Promise<void> {
  if (!fs.existsSync(ARTIFACTS_DIR)) {
    fs.mkdirSync(ARTIFACTS_DIR, { recursive: true });
  }

  const agentReportPath = path.join(ARTIFACTS_DIR, client.reportFileName);

  const existing = await countExistingReviews(allReportTitles);
  if (existing >= MAX_REVIEWS_PER_PR) {
    console.log(`⏭️  Skipping ${client.botName} — ${existing}/${MAX_REVIEWS_PER_PR} reviews already posted.`);
    fs.writeFileSync(
      agentReportPath,
      `## ${client.reportTitle}\n\nSkipped: review quota (${MAX_REVIEWS_PER_PR}) already met.\n`
    );
    return;
  }

  const summary = getCodeDiffSummary();

  if (summary.files.length === 0 || !summary.diffContext) {
    console.log(`✅ No code changes detected — skipping agent review.`);
    fs.writeFileSync(agentReportPath, `## ${client.reportTitle}\n\nNo code changes detected.\n`);
    return;
  }

  console.log(`🤖 Reviewing code diff with ${client.botName}...`);

  const reviewResult = await client.invokeReview(summary);
  const report = generateCodeReviewMarkdown(reviewResult, client);

  // Write local report
  fs.writeFileSync(agentReportPath, report);
  console.log(`✅ Local report written to ${agentReportPath}`);

  // Post to GitHub PR
  await postPRComment(report, client.reportTitle);

  // Write a structured result file alongside the markdown
  const isFail = reviewResult.llmVerdict === 'fail';

  const verdictPath = path.join(ARTIFACTS_DIR, `${client.reportFileName.replace('.md', '')}-verdict.json`);
  fs.writeFileSync(verdictPath, JSON.stringify({
    passed: !isFail,
    highCount: isFail ? 1 : 0,
    routes: [], // To maintain schema compatibility with visual-review if needed
    llmVerdict: reviewResult.llmVerdict
  }, null, 2));

  if (isFail) {
    console.error(`❌ Code review returned FAIL — failing CI.`);
    process.exit(1);
  }
}
