import * as fs from 'fs';
import * as path from 'path';
import { ARTIFACTS_DIR } from './visualReviewConstants';
import { postPRComment, countExistingReviews, getJulesSessionIdFromPR, sendJulesMessage, getPreviousReviewState } from './visualReviewUtils';
import type { CodeReviewSummary, CodeReviewResult, CodeReviewState } from './codeReviewTypes';
import { execSync } from 'child_process';

export interface CodeReviewClientStrategy {
  botName: string;
  reportTitle: string;
  botTagline: string;
  reportFileName: string;
  invokeReview: (summary: CodeReviewSummary) => Promise<CodeReviewResult>;
}

const MAX_REVIEWS_PER_PR = parseInt(process.env.MAX_AI_REVIEWS ?? '10', 10);

async function fetchPRGoal(): Promise<string | undefined> {
  const token = process.env.GITHUB_TOKEN;
  const repo = process.env.GITHUB_REPOSITORY;
  const prNumber = process.env.PR_NUMBER;
  if (!token || !repo || !prNumber) return undefined;

  try {
    const res = await fetch(`https://api.github.com/repos/${repo}/pulls/${prNumber}`, {
      headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' },
    });
    if (!res.ok) return undefined;
    const pr = await res.json() as { title: string; body: string | null };
    const body = pr.body?.trim() ? `\n\n${pr.body.trim()}` : '';
    return `${pr.title}${body}`;
  } catch {
    return undefined;
  }
}

export async function getCodeDiffSummary(): Promise<CodeReviewSummary> {
  try {
    let diffCommand = 'git diff origin/main...HEAD';
    let nameOnlyCommand = 'git diff --name-only origin/main...HEAD';

    // Verify if origin/main exists, fallback to git history for CI if needed
    try {
        execSync('git rev-parse origin/main', { stdio: 'ignore' });
    } catch {
        diffCommand = 'git diff HEAD~1 HEAD';
        nameOnlyCommand = 'git diff --name-only HEAD~1 HEAD';
    }

    const rawDiff = execSync(diffCommand, { encoding: 'utf-8', maxBuffer: 1024 * 1024 * 10 });

    // basic sanity check - just take the first N chars if it's absurdly large to avoid blowing up context
    const maxChars = 20000;
    const diffContext = rawDiff.length > maxChars
      ? rawDiff.slice(0, maxChars) + '\n\n...[TRUNCATED FOR LLM]'
      : rawDiff;

    const fullDiff = rawDiff;

    const files = execSync(nameOnlyCommand, { encoding: 'utf-8' })
      .split('\n')
      .filter(Boolean);

    const prGoal = await fetchPRGoal();

    return {
      files,
      diffContext,
      fullDiff,
      prGoal,
    };
  } catch (error) {
    console.warn('Could not generate code diff:', error);
    return { files: [], diffContext: '' };
  }
}

export function generateCodeReviewMarkdown(
  result: CodeReviewResult,
  client: CodeReviewClientStrategy
): string {
  const prNumber = process.env.PR_NUMBER;
  const prLink = prNumber ? `[PR #${prNumber}](https://github.com/${process.env.GITHUB_REPOSITORY}/pull/${prNumber})` : 'this PR';

  let costLine = '';
  if (result.cost > 0) {
    costLine = `**Cost:** ~$${result.cost.toFixed(5)} (${result.tokens} tokens)\n`;
  }

  return `## ${client.reportTitle}

> ${client.botTagline}

**Reviewing:** ${prLink}
${costLine}

### Code Review Feedback
${result.feedback}

---
*Generated by ${client.botName}*
`;
}

export async function orchestrateCodeReview(
  client: CodeReviewClientStrategy,
  allReportTitles: string[] = []
): Promise<void> {
  if (!fs.existsSync(ARTIFACTS_DIR)) {
    fs.mkdirSync(ARTIFACTS_DIR, { recursive: true });
  }

  const agentReportPath = path.join(ARTIFACTS_DIR, client.reportFileName);

  const existing = await countExistingReviews(allReportTitles);
  if (existing >= MAX_REVIEWS_PER_PR) {
    console.log(`⏭️  Skipping ${client.botName} — ${existing}/${MAX_REVIEWS_PER_PR} reviews already posted.`);
    fs.writeFileSync(
      agentReportPath,
      `## ${client.reportTitle}\n\nSkipped: review quota (${MAX_REVIEWS_PER_PR}) already met.\n`
    );
    const prevState = await getPreviousReviewState<CodeReviewState>(client.reportTitle);
    fs.writeFileSync(path.join(ARTIFACTS_DIR, `${client.reportFileName.replace('.md', '')}-verdict.json`), JSON.stringify({
      passed: true,
      highCount: 0,
      routes: [],
      llmVerdict: 'pass',
      state: prevState
    }, null, 2));
    return;
  }

  const summary = await getCodeDiffSummary();

  // Load previous state and auto-resolve findings that are no longer in the diff
  const prevState = await getPreviousReviewState<CodeReviewState>(client.reportTitle);
  if (prevState?.findings && Array.isArray(prevState.findings)) {
    for (const finding of prevState.findings) {
      if (finding.status === 'open' && finding.snippet) {
        // Use fullDiff for auto-resolution check to avoid truncation issues
        const diffToCheck = summary.fullDiff || summary.diffContext;
        if (!diffToCheck.includes(finding.snippet)) {
          finding.status = 'resolved';
          console.log(`✅ Auto-resolved finding: ${finding.issue}`);
        }
      }
    }
    summary.previousState = prevState;
  }

  if (summary.files.length === 0 || !summary.diffContext) {
    console.log(`✅ No code changes detected — skipping agent review.`);
    fs.writeFileSync(agentReportPath, `## ${client.reportTitle}\n\nNo code changes detected.\n`);
    fs.writeFileSync(path.join(ARTIFACTS_DIR, `${client.reportFileName.replace('.md', '')}-verdict.json`), JSON.stringify({ passed: true, highCount: 0, routes: [], llmVerdict: 'pass' }, null, 2));
    return;
  }

  console.log(`🤖 Reviewing code diff with ${client.botName}...`);

  const reviewResult = await client.invokeReview(summary);
  const report = generateCodeReviewMarkdown(reviewResult, client);

  // Write local report
  fs.writeFileSync(agentReportPath, report);
  console.log(`✅ Local report written to ${agentReportPath}`);

  // Post to GitHub PR
  await postPRComment(report, client.reportTitle, reviewResult.state);

  // Also alert Jules if this PR is from a Jules session
  const julesSessionId = await getJulesSessionIdFromPR();
  if (julesSessionId) {
    const isFail = reviewResult.llmVerdict === 'fail';
    const passFailMsg = isFail ? "FAIL ❌" : "PASS ✅";
    const julesMessage = `[${client.reportTitle}] posted a code review (${passFailMsg}). Please read the review comments on the PR, analyze the diff context provided, and fix any failed or warned areas.`;
    await sendJulesMessage(julesSessionId, julesMessage);
  }

  // Write a structured result file alongside the markdown
  const isFail = reviewResult.llmVerdict === 'fail';

  const verdictPath = path.join(ARTIFACTS_DIR, `${client.reportFileName.replace('.md', '')}-verdict.json`);
  fs.writeFileSync(verdictPath, JSON.stringify({
    passed: !isFail,
    highCount: isFail ? 1 : 0,
    routes: [], // To maintain schema compatibility with visual-review if needed
    llmVerdict: reviewResult.llmVerdict,
    state: reviewResult.state
  }, null, 2));

  if (isFail) {
    console.error(`❌ Code review returned FAIL — failing CI.`);
    process.exit(1);
  }
}
