import * as fs from 'fs';
import * as path from 'path';
import type { RouteReview, VisualRouteSummary } from './visualReviewTypes';
import { DOM_REVIEW_DIR, REVIEW_PROMPT } from './visualReviewConstants';

export function imageToBase64(filePath: string): string {
  return fs.readFileSync(filePath).toString('base64');
}

export function severityEmoji(severity: 'LOW' | 'MEDIUM' | 'HIGH'): string {
  if (severity === 'HIGH') return '🔴';
  if (severity === 'MEDIUM') return '🟡';
  return '🟢';
}

export function buildVisualReviewPayload(summary: VisualRouteSummary): Array<{ type: 'text'; text: string } | { type: 'image_url'; image_url: { url: string } }> {
  const beforePath = summary.beforePath;
  const afterPath = summary.afterPath;
  const diffPath = summary.diffPath;

  // 1. Grab the DOM diff for ground truth
  const domDiffPath = path.join(DOM_REVIEW_DIR, summary.slug, 'diff.txt');
  let domDiffContext = 'No DOM diff available.';
  if (fs.existsSync(domDiffPath)) {
    const diffContent = fs.readFileSync(domDiffPath, 'utf8');
    // Truncate to avoid exploding the context window on massive changes
    domDiffContext = diffContent.length > 3000
      ? diffContent.slice(0, 3000) + '\n...[TRUNCATED]'
      : diffContent;
  }

  // 2. Build the payload
  const baseContent: Array<{ type: 'text'; text: string } | { type: 'image_url'; image_url: { url: string } }> = [
    { type: 'text', text: REVIEW_PROMPT },
    { type: 'text', text: `Route: ${summary.route} | Pixel difference: ${summary.differencePercent.toFixed(2)}% | Severity: ${summary.severity}` },
    { type: 'text', text: `DOM TEXT DIFF:\n\n${domDiffContext}` },
    { type: 'text', text: 'BEFORE' },
    { type: 'image_url', image_url: { url: `data:image/png;base64,${imageToBase64(beforePath)}` } },
    { type: 'text', text: 'AFTER' },
    { type: 'image_url', image_url: { url: `data:image/png;base64,${imageToBase64(afterPath)}` } },
  ];

  if (diffPath && fs.existsSync(diffPath)) {
    baseContent.push(
      { type: 'text', text: 'VISUAL DIFF' },
      { type: 'image_url', image_url: { url: `data:image/png;base64,${imageToBase64(diffPath)}` } }
    );
  }

  return baseContent;
}

export function generateMarkdownReport(
  reviews: RouteReview[],
  botName: string,
  reportTitle: string,
  botTagline: string
): string {
  const highCount = reviews.filter(r => r.severity === 'HIGH').length;
  const medCount = reviews.filter(r => r.severity === 'MEDIUM').length;
  const lowCount = reviews.filter(r => r.severity === 'LOW').length;

  const totalCost = reviews.reduce((acc, r) => acc + r.cost, 0);
  const totalTokens = reviews.reduce((acc, r) => acc + r.tokens, 0);

  const prNumber = process.env.PR_NUMBER;
  const prLink = prNumber ? `[PR #${prNumber}](https://github.com/${process.env.GITHUB_REPOSITORY}/pull/${prNumber})` : 'this PR';

  const sections = reviews.map(r => `
### ${severityEmoji(r.severity)} \`${r.route}\`

**Pixel diff:** ${r.differencePercent.toFixed(2)}%

${r.feedback}
`).join('\n---\n');

  let costLine = '';
  if (totalCost > 0) {
    costLine = `**Cost:** ~$${totalCost.toFixed(5)} (${totalTokens} tokens)\n`;
  }

  return `## ${reportTitle}

> ${botTagline}

**Summary:** 🔴 ${highCount} high · 🟡 ${medCount} medium · 🟢 ${lowCount} low
**Reviewing:** ${prLink}
${costLine}
${sections}

---
*Generated by ${botName} — [Blast-Radius Analyzer](https://boomtick.blog/research)*
`;
}

export async function postPRComment(body: string, reportTitle: string): Promise<void> {
  const token = process.env.GITHUB_TOKEN;
  const repo = process.env.GITHUB_REPOSITORY;
  const prNumber = process.env.PR_NUMBER;

  if (!token || !repo || !prNumber) {
    console.warn('⚠️  Skipping PR comment — GITHUB_TOKEN, GITHUB_REPOSITORY, or PR_NUMBER not set.');
    return;
  }

  const url = `https://api.github.com/repos/${repo}/issues/${prNumber}/comments`;

  // Check for existing comments from this bot to avoid spamming the PR
  const getCommentsResponse = await fetch(url, {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
    },
  });

  if (getCommentsResponse.ok) {
    const comments = await getCommentsResponse.json() as Array<{
      id: number;
      body: string;
      user: { type: string };
    }>;
    const existingComment = comments.find(c =>
      c.user.type === 'Bot' && c.body.includes(`## ${reportTitle}`)
    );

    if (existingComment) {
      const updateUrl = `https://api.github.com/repos/${repo}/issues/comments/${existingComment.id}`;
      const updateResponse = await fetch(updateUrl, {
        method: 'PATCH',
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: 'application/vnd.github+json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ body }),
      });

      if (!updateResponse.ok) {
        const text = await updateResponse.text();
        throw new Error(`GitHub API error ${updateResponse.status}: ${text}`);
      }

      console.log('✅ Updated existing PR comment');
      return;
    }
  }

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ body }),
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`GitHub API error ${response.status}: ${text}`);
  }

  console.log('✅ Posted PR comment');
}
