from typing import Any, List, Literal, Optional, Union
from pydantic import BaseModel, ConfigDict, Field, HttpUrl

from wcs_navigator_api.models.logistics import AgentDecisionTrace


class DiscoverUrlRequest(BaseModel):
    """Payload for Stage 1 URL pre-scan discovery request."""

    url: HttpUrl


class FormQuestionOption(BaseModel):
    """Structured option for select / multiselect questionnaire items."""

    model_config = ConfigDict(populate_by_name=True)

    label: str
    value: Union[str, bool, int, float]
    subtitle: Optional[str] = None
    badge: Optional[str] = None


class FormQuestion(BaseModel):
    """Dynamic form question generated by Gemini in Discovery pass."""

    model_config = ConfigDict(populate_by_name=True)

    id: str
    title: str = Field(alias="title")
    type: Literal["select", "multiselect", "boolean"]
    context: str  # P0: Explainability justification for why this question exists
    required: Optional[bool] = False
    options: Optional[List[FormQuestionOption]] = Field(default_factory=list)
    default_value: Optional[Union[str, bool, int, float, List[Union[str, bool, int, float]]]] = Field(
        default=None, alias="defaultValue"
    )


class DiscoveryResponse(BaseModel):
    """Structured response returned by Stage 1 Discovery pass."""

    model_config = ConfigDict(populate_by_name=True)

    preset_id: Optional[str] = Field(default=None, alias="preset_id")
    preset_name: Optional[str] = Field(default=None, alias="preset_name")
    event_name: Optional[str] = Field(default=None, alias="event_name")
    tracks_detected: Optional[List[str]] = Field(default_factory=list)
    suggested_form_questions: List[FormQuestion] = Field(default_factory=list)


class GenerateUrlRequest(BaseModel):
    """Payload for Stage 2 schedule generation request via URL."""

    url: HttpUrl
    questionnaire_responses: dict[str, Any]


class GenerateResponse(BaseModel):
    """Structured response returned by Stage 2 Generation pass."""

    model_config = ConfigDict(populate_by_name=True)

    decision_trace: AgentDecisionTrace = Field(alias="decisionTrace")
    ics_content: str = Field(alias="icsContent")
    visual_schedule_markdown: Optional[str] = Field(default="", alias="visualScheduleMarkdown")

