import os
import sys
import google.generativeai as genai
from github import Github

def main():
    gemini_key = os.getenv("GEMINI_API_KEY")
    github_token = os.getenv("GITHUB_TOKEN")
    issue_number = os.getenv("ISSUE_NUMBER")
    issue_body = os.getenv("ISSUE_BODY")
    issue_title = os.getenv("ISSUE_TITLE")
    repo_name = os.getenv("REPO_FULL_NAME")

    if not all([gemini_key, github_token, issue_number, issue_body, repo_name]):
        print("Missing required environment variables.")
        sys.exit(1)

    # 1. Initialize Gemini
    genai.configure(api_key=gemini_key)
    model = genai.GenerativeModel('gemini-1.5-flash')

    prompt = f"""
    You are the 'Tech-Dancer' content automation agent.
    Your task is to take a raw content draft submitted via a GitHub Issue and transform it into a high-quality, SEO-optimized Markdown file for a lifestyle blog.

    User Persona: An enthusiastic, tech-savvy West Coast Swing dancer.
    Tone: Professional yet organic and community-focused.

    Raw Title: {issue_title}
    Raw Content: {issue_body}

    Instructions:
    1. Refine the title to be catchy but SEO-friendly.
    2. Expand on the content, ensuring it provides "Meaningful Value" to the Tech-Dancer demographic.
    3. Include placeholder affiliate link structures if products are mentioned.
    4. Format the output as a valid Markdown file with frontmatter (title, date, labels).
    5. Return ONLY the markdown content.
    """

    response = model.generate_content(prompt)
    markdown_content = response.text

    # 2. Initialize GitHub
    g = Github(github_token)
    repo = g.get_repo(repo_name)

    # Create a new branch
    branch_name = f"content-issue-{issue_number}"
    base_branch = repo.default_branch
    sb = repo.get_branch(base_branch)
    repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=sb.commit.sha)

    # 3. Create the file in the new branch
    file_path = f"content/post-{issue_number}.md"
    repo.create_file(
        path=file_path,
        message=f"Add content from issue #{issue_number}",
        content=markdown_content,
        branch=branch_name
    )

    # 4. Open a Pull Request
    pr = repo.create_pull(
        title=f"Content Update: {issue_title}",
        body=f"Closes #{issue_number}. Automatically generated by Tech-Dancer Pipeline.",
        head=branch_name,
        base=base_branch
    )

    print(f"Successfully created PR: {pr.html_url}")

if __name__ == "__main__":
    main()
