import fs from 'fs';
import path from 'path';

const distDir = path.resolve(process.cwd(), 'dist');
const indexPath = path.join(distDir, 'index.html');

if (!fs.existsSync(indexPath)) {
  console.error('❌ Build failed: index.html not found in dist/');
  process.exit(1);
}

const html = fs.readFileSync(indexPath, 'utf-8');

// The expected base path for GitHub Pages, allowing override from environment
const expectedBase = process.env.VITE_BASE_PATH || '/tech-dancer/';

console.log(`--- Build Asset Check (Expected Base: ${expectedBase}) ---`);

const scriptRegex = /src="([^"]+)"/g;
const styleRegex = /href="([^"]+)"/g;

const scriptMatches = [...html.matchAll(scriptRegex)];
const styleMatches = [...html.matchAll(styleRegex)];

let failed = false;

for (const match of scriptMatches) {
  const src = match[1];
  // Ignore external URLs and data URIs
  if (src.startsWith('http') || src.startsWith('//') || src.startsWith('data:')) continue;

  if (!src.startsWith(expectedBase)) {
    console.error(`❌ FAILURE: Script path "${src}" does not start with "${expectedBase}"`);
    failed = true;
  }
}

for (const match of styleMatches) {
  const href = match[1];
  // Only check internal CSS/assets
  if (href.startsWith('http') || href.startsWith('//') || href.startsWith('data:')) continue;

  // We primarily care about assets generated by the build
  if (href.includes('assets/') && !href.startsWith(expectedBase)) {
    console.error(`❌ FAILURE: Asset path "${href}" does not start with "${expectedBase}"`);
    failed = true;
  }
}

if (failed) {
  console.error('Check your vite.config.ts "base" setting.');
  process.exit(1);
}

console.log('✅ Success: Asset paths are correctly prefixed for deployment.');
