import os
import sys
from github import Github, Auth

def get_github_token():
    return os.getenv("CODEX_GH_TOKEN") or os.getenv("GH_TOKEN") or os.getenv("GITHUB_TOKEN") or os.getenv("PAT_TOKEN")

def post_audit_comment(issue, recommendation, reason, evidence, remaining="None"):
    comment = f"""## Issue audit result

**Recommendation:** {recommendation}

**Reason:**
{reason}

**Implementation evidence:**
{evidence}

**Remaining work:**
{remaining}

---
*Generated by triage agent*"""
    issue.create_comment(comment)
    if "close" in recommendation.lower():
        issue.edit(state="closed")
    print(f"Updated Issue #{issue.number}: {recommendation}")

def main():
    token = get_github_token()
    if not token:
        print("No GitHub token found")
        sys.exit(1)

    g = Github(auth=Auth.Token(token))
    repo = g.get_repo("arii/tech-dancer")

    # Issue #1867
    issue_1867 = repo.get_issue(1867)
    post_audit_comment(
        issue_1867,
        "Outdated, close",
        "The GearShelf component and the /gear page have been decommissioned. The remaining About page spacing issues have been addressed by the migration to design system primitives (Stack, Box, Grid) which handle spacing consistently.",
        "- Files checked: `src/pages/About.tsx`, `src/features/profile/ArielProfile.tsx`\n- Components verified: `GearShelf` removed from codebase.",
    )

    # Issue #1863
    issue_1863 = repo.get_issue(1863)
    post_audit_comment(
        issue_1863,
        "Completed, close",
        "The 'Have a Design Idea?' suggestion card has been removed from the /merch page because the contact page is hidden. The footer layout was simplified to a single full-width ReferralBanner, resolving the visual rhythm mismatch.",
        "- Files checked: `src/pages/Merch.tsx`\n- Validation: `pnpm run audit` and `pnpm run lint` passed.",
    )

    # Issue #2208
    issue_2208 = repo.get_issue(2208)
    post_audit_comment(
        issue_2208,
        "Completed, close",
        "All 9 gear-focused blog posts have been added to `content/posts/`, mapping the items in `affiliates.json`.",
        "- Files checked: `content/posts/` (verified 17 posts exist, including the new gear essentials)\n- Related PR: #2212",
    )

    # Issue #2211
    issue_2211 = repo.get_issue(2211)
    if issue_2211.state == "open":
        post_audit_comment(
            issue_2211,
            "Completed, close",
            "Event Resource Guides have been successfully removed. Routes, markdown guides, and layout lists have been cleaned up.",
            "- Files checked: `src/config/routes.ts` (verified /events routes point to RemovedPage)",
        )
    else:
        print(f"Issue #2211 is already {issue_2211.state}. Skipping.")

if __name__ == "__main__":
    main()
