name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - .devcontainer/Dockerfile

# Permissions required to write to GitHub Packages

jobs:
  call-workflow:
    uses: ./boomtick-pkg/workflows/deploy-image.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
