name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - .devcontainer/Dockerfile

permissions:
  contents: read
  packages: write

jobs:
  deploy-image:
    uses: ./boomtick-pkg/workflows/deploy-image-reusable.yml
    secrets: inherit # nosemgrep: yaml.github-actions.security.secrets-inherit.secrets-inherit
