name: Deploy to GitHub Pages

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./boomtick-pkg/workflows/deploy.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pages: write
      id-token: write
      pull-requests: write
      issues: write
