name: Issue to Content PR

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  issue-to-pr:
    uses: ./boomtick-pkg/workflows/issue-to-pr-reusable.yml
    secrets: inherit # nosemgrep: yaml.github-actions.security.secrets-inherit.secrets-inherit
