name: Issue Comment Dispatcher

on:
  issue_comment:
    types: [created]

jobs:
  call-workflow:
    uses: ./boomtick-pkg/workflows/issue-comment-dispatcher.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
