name: Issue to Content PR

on:
  issues:
    types: [opened, edited]

jobs:
  call-workflow:
    uses: ./boomtick-pkg/workflows/issue_to_pr.yml
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
      issues: read
