name: Auto-Resolve Merge Conflicts

on:
  pull_request:
    types: [opened, synchronize, reopened]


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow:
    uses: ./boomtick-pkg/workflows/mergellama.yml
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
