name: Release Please

on:
  push:
    branches:
      - leader

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: self-hosted
    steps:
      - uses: googleapis/release-please-action@8b8fd2cc23b2e18957157a9d923d75aa0c6f6ad5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          config-file: release-please-config.json
