name: Self-Healing CI

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  call-workflow:
    uses: ./boomtick-pkg/workflows/self-healing.yml
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
      actions: read
