name: Update Playwright Snapshots

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number'
        required: true
        type: string
      comment_body:
        description: 'Comment body'
        required: true
        type: string

jobs:
  call-workflow:
    uses: ./boomtick-pkg/workflows/update-snapshots.yml
    with:
      issue_number: ${{ inputs.issue_number }}
      comment_body: ${{ inputs.comment_body }}
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
      actions: write
