name: Validate Issue Quality

on:
  issues:
    types: [opened, edited]

jobs:
  call-workflow:
    uses: ./boomtick-pkg/workflows/validate_issue.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
