name: Workflow Validation


on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - '.yamllint.yml'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - '.yamllint.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow:
    uses: ./boomtick-pkg/workflows/workflow-validation.yml
    secrets: inherit
    permissions:
      contents: read
